# -*- coding: utf-8 -*-
"""Vocações (Sessão 6) e Carreiras (Sessão 16) como itens de definição."""
from builders import definicao
from data_tracos import TRACOS
from data_tracos_2 import TRACOS_2

_ALL_TRACOS = {t["name"]: t for t in (TRACOS + TRACOS_2)}
IMG_VOC = "icons/svg/combat.svg"
IMG_CAR = "icons/svg/upgrade.svg"
_PAL = "Palavra Arcana"


def _voc(nome, desc, hp, mp, skills):
    return definicao(
        nome, "vocacao",
        desc + f"\n\nBônus de Pontos de Vida: +{hp}. Bônus de Pontos de Magia: +{mp}.",
        skill_list=skills, hpBonus=hp, mpBonus=mp, img=IMG_VOC,
    )


VOCACOES = [
    _voc("Bárbaro",
         "Combatentes selvagens movidos pela fúria, resistentes e devastadores no corpo a corpo.",
         4, 0,
         ["Acrobacia", "Alerta", "Atletismo", "Carregador", "Combater sem Armadura",
          "Conhecimento (Natureza)", "Corredor", "Medicina", "Montar Criatura", "Sobrevivência",
          "Usar Armaduras Leves", "Usar Armas (Arremesso)", "Usar Armas (Duas Mãos)",
          "Usar Armas (Militar)", "Usar Armas (Simples)", "Usar Armas (Uma Mão)", "Usar Escudos",
          "Contragolpe", "Espírito Guardião (Qualquer)", "Fúria", "Golpe Crítico Brutal",
          "Grito de Guerra", "Guerreiro Incauto", "Ímpeto", "Melhorar Atributo (Força)",
          "Melhorar Atributo (Vigor)", "Presença Aterradora", "Reação Furiosa", "Reflexos",
          "Sem Brechas", "Velocidade de Ataque", "Vigor de Aço"]),
    _voc("Bardo",
         "Artistas e eruditos que inspiram aliados com música, lábia e conhecimento vasto.",
         2, 2,
         ["Canção do Viajante", "Carisma", "Conhecimento (Arcano)", "Conhecimento (Guerra)",
          "Conhecimento (História)", "Conhecimento (Natureza)", "Especialista", "Inspirar",
          "Lidar com Armadilhas", "Lidar com Animais", "Medicina", "Melhorar Atributo (Agilidade)",
          "Melhorar Atributo (Mente)", "Mercado Negro", "Mestre do Conhecimento",
          "Montar Criatura", "Ofícios", f"{_PAL} (carmo)", f"{_PAL} (iluzio)", f"{_PAL} (inanis)",
          f"{_PAL} (sonigu)", f"{_PAL} (sorcdiron)", f"{_PAL} (traumato)", f"{_PAL} (vitae)",
          "Sobrevivência", "Usar Armaduras Leves", "Usar Armas (Bestas)",
          "Usar Armas (Lâminas Pequenas)", "Usar Armas (Simples)"]),
    _voc("Bruxo",
         "Conjuradores que obtêm poder por meio de pactos com entidades extraplanares.",
         2, 0,
         ["Carisma", "Conhecimento (Arcano)", "Conhecimento (História)", "Conhecimento (Natureza)",
          "Conhecimento (Ocultismo)", "Conhecimento (Religião)", "Estudos Místicos", "Familiar",
          "Linguista Arcano", "Magia Sem Gestos", "Magia Sem Materiais", "Magia Silenciosa",
          "Melhorar Atributo (Mente)", "Melhorar Atributo (Vigor)", "Mercado Negro",
          "Pacto (Qualquer)", "Usar Armaduras Leves", "Usar Armas (Simples)", "Vontade de Ferro"]),
    _voc("Clérigo",
         "Servos devotos que canalizam os aspectos de sua divindade em milagres.",
         2, 0,
         ["Carisma", "Conhecimento (Religião)", "Escolhido da Divindade", "Guerra Santa",
          "Guerreiro da Fé", "Guia Divino", "Magia Unilateral", "Medicina",
          "Melhorar Atributo (Mente)", "Prece de Repouso", "Primeiro Aspecto", "Segundo Aspecto",
          "Usar Armaduras Leves", "Usar Armas (Simples)"]),
    _voc("Druida",
         "Guardiões da natureza que conjuram seus ciclos e assumem formas animais.",
         2, 2,
         ["Atletismo", "Carisma", "Companheiro Animal", "Conhecimento (Arcano)",
          "Conhecimento (História)", "Conhecimento (Natureza)", "Conhecimento (Religião)",
          "Espírito Guardião (Qualquer)", "Explorador (Qualquer)", "Forma Animal",
          "Lidar com Animais", "Magia Unilateral", "Medicina", "Melhorar Atributo (Mente)",
          "Melhorar Atributo (Percepção)", f"{_PAL} (devena)", f"{_PAL} (krucigon)",
          f"{_PAL} (noxia)", f"{_PAL} (sangon)", "Sobrevivência", "Trilhador (Qualquer)",
          "Usar Armaduras Leves", "Usar Armas (Simples)"]),
    _voc("Guardião",
         "Defensores implacáveis que protegem aliados e controlam o campo de batalha.",
         4, 0,
         ["Atletismo", "Baluarte", "Carregador", "Contragolpe", "Golpear com Escudo", "Ímpeto",
          "Medicina", "Melhorar Atributo (Força)", "Melhorar Atributo (Vigor)", "Montar Criatura",
          "Proteger", "Provocar", "Recuperar o Fôlego", "Sentido Sísmico", "Táticas de Grupo",
          "Usar Armas (Arremesso)", "Usar Armas (Artilharia)", "Usar Armas (Militar)",
          "Usar Armas (Simples)", "Usar Armas (Uma Mão)", "Usar Escudos", "Veículos (Terrestres)",
          "Vigor de Aço", "Zona de Ameaça"]),
    _voc("Guerreiro",
         "Mestres das armas e das táticas, versáteis em qualquer estilo de combate.",
         3, 0,
         ["Acrobacia", "Alerta", "Atletismo", "Baluarte", "Carisma", "Carregador",
          "Conhecimento (Guerra)", "Contragolpe", "Empunhadura Dupla", "Golpear com Escudo",
          "Ímpeto", "Impulso de Combate", "Medicina", "Melhorar Atributo (Agilidade)",
          "Melhorar Atributo (Força)", "Montar Criatura", "Recuperar o Fôlego", "Saque Rápido",
          "Sobrevivência", "Táticas de Grupo", "Usar Armaduras Leves", "Usar Armas (Arremesso)",
          "Usar Armas (Artilharia)", "Usar Armas (Corpo a Corpo)", "Usar Armas (Duas Mãos)",
          "Usar Armas (Militar)", "Usar Armas (Simples)", "Usar Armas (Uma Mão)", "Usar Escudos",
          "Veículos (Terrestres)", "Velocidade de Ataque"]),
    _voc("Ladino",
         "Especialistas em furtividade, precisão e golpes oportunos.",
         2, 0,
         ["Acrobacia", "Alerta", "Ameaça Invisível", "Atirador", "Atletismo", "Carisma",
          "Desengajar", "Especialista", "Furtividade", "Golpe Cegante", "Golpe de Sorte",
          "Letalidade", "Lidar com Armadilhas", "Melhorar Atributo (Agilidade)",
          "Melhorar Atributo (Percepção)", "Mercado Negro", "Movimento Astuto", "Reflexos",
          "Saque Rápido", "Sem Brechas", "Usar Armaduras Leves", "Usar Armas (Arremesso)",
          "Usar Armas (Artilharia)", "Usar Armas (Lâminas Pequenas)"]),
    _voc("Mago",
         "Estudiosos das palavras arcanas, com o mais amplo repertório de magias.",
         1, 3,
         ["Carisma", "Conhecimento (História)", "Conhecimento (Religião)", "Escola Arcana",
          "Familiar", "Implemento Arcano Superior", "Linguista Arcano", "Medicina",
          "Melhorar Atributo (Mente)", f"{_PAL} (acida)", f"{_PAL} (augurado)",
          f"{_PAL} (energio)", f"{_PAL} (fulgur)", f"{_PAL} (glacios)", f"{_PAL} (ignis)",
          f"{_PAL} (iluzio)", f"{_PAL} (inanis)", f"{_PAL} (kreo)", f"{_PAL} (krucigon)",
          f"{_PAL} (lumo)", f"{_PAL} (mortis)", f"{_PAL} (noxia)", f"{_PAL} (sonigu)",
          f"{_PAL} (sorcdiron)", f"{_PAL} (tenebrae)", "Preparação Arcana",
          "Usar Armas (Simples)"]),
    _voc("Monge",
         "Ascetas disciplinados que transformam o próprio corpo em arma.",
         2, 1,
         ["Acrobacia", "Alerta", "Artes Marciais", "Atletismo", "Combater às Cegas",
          "Combater sem Armadura", "Conhecimento (Arcano)", "Conhecimento (Natureza)",
          "Conhecimento (Religião)", "Corredor", "Defletir Projéteis", "Desengajar", "Furtividade",
          "Medicina", "Melhorar Atributo (Agilidade)", "Melhorar Atributo (Força)",
          "Melhorar Atributo (Mente)", "Ofícios", f"{_PAL} (sorcdiron)", "Reflexos", "Sem Brechas",
          "Usar Armas (Desarmado)", "Usar Armas (Simples)", "Velocidade de Ataque", "Vigor de Aço",
          "Vontade de Ferro"]),
    _voc("Paladino",
         "Guerreiros sagrados unidos por juramentos e pela fé em sua divindade.",
         3, 1,
         ["Alerta", "Atletismo", "Baluarte", "Carisma", "Conhecimento (História)",
          "Conhecimento (Religião)", "Golpear com Escudo", "Guerra Santa", "Ímpeto",
          "Juramento (Qualquer)", "Medicina", "Melhorar Atributo (Força)",
          "Melhorar Atributo (Mente)", "Montar Criatura", f"{_PAL} (sorcdiron)", f"{_PAL} (vitae)",
          "Prece de Repouso", "Presença Aterradora", "Proteger", "Punição", "Usar Armaduras Leves",
          "Usar Armas (Duas Mãos)", "Usar Armas (Militar)", "Usar Armas (Simples)",
          "Usar Armas (Uma Mão)", "Usar Escudos", "Vigor de Aço", "Vontade de Ferro"]),
    _voc("Patrulheiro",
         "Caçadores e rastreadores dos ermos, mortais com arcos e armas duplas.",
         2, 0,
         ["Acrobacia", "Alerta", "Atirador", "Atirador em Movimento", "Atletismo",
          "Combater às Cegas", "Companheiro Animal", "Conhecimento (Natureza)",
          "Empunhadura Dupla", "Exímio Atirador", "Furtividade", "Lidar com Animais",
          "Melhorar Atributo (Agilidade)", "Melhorar Atributo (Percepção)", "Montar Criatura",
          "Predador Astuto", "Recarga Rápida", "Saque Rápido", "Sobrevivência",
          "Trilhador (Qualquer)", "Usar Armas (Arremesso)", "Usar Armas (Simples)",
          "Usar Armas (Uma Mão)", "Usar Escudos", "Velocidade de Ataque"]),
]


def _car(nome, desc, prereq, granted_name, skills):
    return definicao(
        nome, "carreira",
        desc + "\n\n" + prereq,
        skill_list=skills,
        granted=[_ALL_TRACOS[granted_name]],
        img=IMG_CAR,
    )


CARREIRAS = [
    _car("Arquimago",
         "Estudiosos avançados das magias, capazes de liberar o fluxo arcano dentro de si e moldar magias no ato da conjuração. Magos e Bruxos se tornam aptos mais rapidamente a assumir esta carreira.",
         "Pré-requisitos — Corrupção: Qualquer. Raça: Qualquer. Tempo Necessário: 60 dias de estudos em uma escola arcana. Habilidades Necessárias: Palavra Arcana (Qualquer) [A], Preparação Arcana [B], Conhecimento (Arcano) [A], Linguista Arcano [A].\n\nCaracterísticas: +2 Pontos de Magia Máximos.",
         "Característica do Arquimago",
         ["Alta Arcana", "Fluxo Arcano", "Magia Sem Gestos", "Magia Sem Materiais",
          "Magia Silenciosa", "Mestre Conjurador", "Mestre do Conhecimento"]),
    _car("Assassino",
         "Especialistas em eliminar vítimas sem serem vistos, precisos, letais e hábeis com venenos. Ladinos se tornam aptos mais rapidamente a assumir esta carreira.",
         "Pré-requisitos — Corrupção: 6+. Raça: Qualquer. Tempo Necessário: 60 dias e testes em uma guilda de assassinos. Habilidades Necessárias: Ameaça Invisível [A], Golpe Cegante [B], Letalidade [A], Movimento Astuto [A].\n\nCaracterísticas: +1 Ponto de Vida Máximo.",
         "Característica do Assassino",
         ["Contragolpe", "Desaparecer", "Golpe Letal", "Lidar com Venenos", "Sem Falhas",
          "Velocidade de Ataque"]),
    _car("Legionário",
         "Combatentes veteranos de trincheira, treinados para enfrentar grandes unidades sozinhos, equilibrando ataque e defesa. Guerreiros, Guardiões e Paladinos se tornam aptos mais rapidamente a assumir esta carreira.",
         "Pré-requisitos — Corrupção: Qualquer. Raça: Qualquer. Tempo Necessário: 60 dias atuando em guerras. Habilidades Necessárias: Conhecimento (Guerra) [A], Sobrevivência [B], Recuperar o Fôlego [A], Ímpeto [A].\n\nCaracterísticas: +3 Pontos de Vida Máximos.",
         "Característica do Legionário",
         ["Carregador", "Corredor", "Desengajar", "Enfrentar a Horda", "Firmeza Física",
          "Golpe Giratório", "Golpear com Escudo", "Grito de Guerra", "Impulso de Combate",
          "Proteger", "Usar Escudos", "Velocidade de Ataque"]),
    _car("Sacerdote",
         "Autoridades de alta escala na hierarquia religiosa, os mortais mais próximos de sua divindade, capazes de manifestar parcialmente seu poder em combate. Clérigos se tornam aptos mais rapidamente a assumir esta carreira.",
         "Pré-requisitos — Corrupção: Qualquer. Raça: Qualquer. Tempo Necessário: 60 dias de estudos e trabalhos a serviço da igreja de sua divindade. Habilidades Necessárias: Primeiro Aspecto [A], Segundo Aspecto [A], Guerreiro da Fé [B], Escolhido da Divindade [B].\n\nCaracterísticas: +1 Ponto de Vida Máximo.",
         "Característica do Sacerdote",
         ["Autoridade Divina", "Manifestação Divina", "Terceiro Aspecto"]),
]
