# -*- coding: utf-8 -*-
"""Habilidades — parte 1 (A–E). Fonte: Livro de Regras, Sessão 9."""
from builders import habilidade, effect, cost, action, applies

IMG = {
    "combate": "icons/svg/sword.svg",
    "pericia": "icons/svg/book.svg",
    "magia": "icons/svg/daze.svg",
    "social": "icons/svg/angel.svg",
    "corpo": "icons/svg/regen.svg",
    "fera": "icons/svg/pawprint.svg",
}

HABILIDADES_1 = [
    habilidade(
        "Acrobacia",
        "Pequenino, bárbaro, guerreiro, ladino, monge e patrulheiro.",
        "Você recebe 1D em rolagens de atividades acrobáticas (evitar queda, andar na corda bamba, atravessar um espaço ocupado...).",
        "Você recebe 1 Ponto adicional em Esquiva. Seus resultados 11 ou 12 em rolagens de Esquiva são sucessos críticos. Quando uma criatura se move adjacente a você, você pode pagar 1 ponto heróico e usar sua reação para imediatamente se mover sem sofrer reações de ataque.",
        10, 30,
        effects=[
            effect("bonus", "esquiva", 1, level="A", label="Acrobacia (A): +1 Esquiva"),
            effect("crit", "esquiva", 1, level="A", label="Acrobacia (A): crítico 11-12 em Esquiva"),
        ],
        img=IMG["corpo"],
    ),
    *[
        habilidade(
            f"Afinidade Mágica Elemental ({nome})",
            "Draconiano e infernal",
            f"Você possui afinidade com o elemento {nome} e causa 1 ponto de dano bruto adicional quando conjura magias relacionadas ao elemento especificado (palavra arcana {palavra}).",
            "O dano bruto adicional causado aumenta para 3 pontos de dano.",
            20, 40, prereq="Mente 4+",
            effects=[
                effect("damage", "all", 1, level="B", label=f"Afinidade ({nome}) B: +1 dano", damage_type=dtipo),
                effect("damage", "all", 2, level="A", label=f"Afinidade ({nome}) A: +2 dano (total 3)", damage_type=dtipo),
            ],
            img=IMG["magia"],
        )
        for nome, palavra, dtipo in [
            ("Ácido", "acida", "acido"),
            ("Gelo", "glacios", "frio"),
            ("Fogo", "ignis", "fogo"),
            ("Raio", "fulgur", "raio"),
            ("Veneno", "noxia", "veneno"),
        ]
    ],
    habilidade(
        "Alerta",
        "Gnomos das Profundezas, pequenino, bárbaro, guerreiro, ladino, monge, paladino, patrulheiro, clérigo (Krimmena e Meriak)",
        "Você recebe 1D em rolagens para descobrir coisas escondidas, encontrar pistas, notar detalhes de um ambiente e tentar escutar sons específicos.",
        "Você recebe +4 na Iniciativa. Você recebe 1D em rolagens para perceber armadilhas e ameaças naturais. Adicionalmente, você recebe um bônus igual a metade do seu nível em rolagens para resistir e anular condições de Cego e Surdo.",
        10, 30,
        effects=[effect("bonus", "iniciativa", 4, level="A", label="Alerta (A): +4 Iniciativa")],
        img=IMG["pericia"],
    ),
    habilidade(
        "Ameaça Invisível",
        "Ladino",
        "Quando você está escondido e faz um ataque, caso acerte e o alvo chegue a 0 pontos de vida, você pode fazer uma rolagem de Agilidade para permanecer escondido.",
        "Caso você erre o ataque, ou caso a vítima não chegue a 0 pontos de vida, você pode gastar 1 ponto heróico para permanecer escondido. Testes para permanecer escondido usando esta habilidade recebem 1D. Quando você ataca enquanto está escondido e acerta, pode gastar 1 ponto heróico para obter um sucesso crítico nesse ataque.",
        20, 40, prereq="Agilidade 4+",
        img=IMG["combate"],
    ),
    habilidade(
        "Artes Marciais",
        "Monge",
        "Quando faz ataques desarmados, você pode rolar Agilidade em vez de Força. Seus ataques desarmados causam um dano base igual a metade do seu nível (arredondado para cima).",
        "Seus ataques desarmados causam um dano base igual ao seu nível. Quando você faz um ataque desarmado e acerta o alvo, você pode escolher deixar o alvo pasmo (ou deixá-lo atordoado, pagando 1 ponto heróico) (Vigor anula), em vez de aplicar dano.",
        20, 40,
        activation="Ação (ataque)",
        actions=[action(
            "Ataque Desarmado Marcial (ajuste o dano: B = metade do Nível; A = Nível)",
            roll_attr="agilidade", damage="1", damage_type="concussao",
            defense_attr="esquiva", defense_attr2="bloqueio",
        )],
        img=IMG["combate"],
    ),
    habilidade(
        "Atirador",
        "Ladino",
        "Você pode gastar seu movimento para não sofrer reações de ataque quando fizer ataques à distância nesse turno.",
        "Você pode gastar sua ação rápida para não sofrer reações de ataque quando fizer ataques à distância nesse turno. Você pode gastar seu movimento para receber 1D nos seus ataques à distância nesse turno. Caso você não se mova no mesmo turno em que atacar, você pode gastar 1 ponto heróico, quando acertar um ataque à distância para que ele se torne um acerto crítico.",
        20, 40,
        img=IMG["combate"],
    ),
    habilidade(
        "Atirador em Movimento",
        "Patrulheiro",
        "Quando gastar seu movimento para mirar, você ainda pode mover-se metade de seu Deslocamento.",
        "Você pode mirar usando sua ação rápida, em vez de seu movimento.",
        20, 40,
        img=IMG["combate"],
    ),
    habilidade(
        "Atletismo",
        "Meio-orc, pequenino, bárbaro, druida, guardião, guerreiro, ladino, monge, paladino, patrulheiro, clérigo (Garlock e Iperon).",
        "Você recebe 1D em rolagens de atividades atléticas (saltar, nadar, escalar...).",
        "Você recebe 1 ponto adicional no atributo Bloqueio. Resultados naturais 11 ou 12 em suas rolagens de Bloqueio são sucessos críticos. Você pode gastar 1 ponto heróico para considerar um sucesso crítico em uma rolagem de qualquer atividade atlética fora do combate.",
        10, 30,
        effects=[
            effect("bonus", "bloqueio", 1, level="A", label="Atletismo (A): +1 Bloqueio"),
            effect("crit", "bloqueio", 1, level="A", label="Atletismo (A): crítico 11-12 em Bloqueio"),
        ],
        img=IMG["corpo"],
    ),
    habilidade(
        "Baluarte",
        "Anão das montanhas, guardião, guerreiro, paladino, clérigo (Hipóferus, Kovar, Lohanost, Rhyfel, Pálim, Garganór e Válor).",
        "Enquanto você estiver vestindo armadura, sua penalidade por usar armadura é reduzida em 1 ponto.",
        "Você pode usar sua ação rápida e gastar 1 ponto heróico para dobrar a Proteção de sua armadura até que você sofra dano.",
        10, 30, prereq="Vigor 4+",
        img=IMG["combate"],
    ),
    habilidade(
        "Bastião de Esperança",
        "Terras Centrais",
        "Para cada aliado inconsciente em batalha, você recebe +1 nas rolagens de defesa. Você ignora 1 ponto de dano de queda, armadilhas e doenças.",
        "O bônus por aliado caído é aplicado também às rolagens para anular condições. O dano ignorado aumenta para 2 pontos. Adicionalmente, você fica imune à condição Exausto.",
        10, 30,
        img=IMG["social"],
    ),
    habilidade(
        "Canção do Viajante",
        "Bardo",
        "Você entoa canções que tranquilizam, entretêm e relaxam as mentes de seus aliados. Seus aliados recuperam 1 ponto de vida adicional quando descansam.",
        "Seus aliados recuperam 2 pontos de vida e 1 ponto de magia adicionais, quando descansam.",
        10, 30,
        img=IMG["social"],
    ),
    habilidade(
        "Carisma",
        "Anão das terras baixas, elfo das profundezas, gnomo da floresta, gnomo das rochas, meio-elfo, celestial, draconiano, infernal, bardo, bruxo, clérigo, druida, guerreiro, ladino, mago, monge e paladino.",
        "Você recebe 1D em rolagens de interação social (diplomacia, blefar, intimidar...).",
        "Você pode gastar 1 ponto heróico para conceder +1 em todas as rolagens de aliados que possam ouvi-lo ou -1 em todas as rolagens de inimigos que possam ouvi-lo (não anula). Esse efeito dura até o fim da cena.",
        10, 30,
        activation="Livre (nível A)",
        actions=[
            action("Presença Carismática (A): +1 aliados que possam ouvi-lo",
                   can_roll=False, target_mode="aura", area=20, cost_heroic=1,
                   applies_effects=[applies("Carisma: +1 em todas as rolagens", fx_type="bonus",
                                            fx_target="all", fx_value=1, duration_mode="scene")]),
            action("Presença Carismática (A): -1 inimigos que possam ouvi-lo",
                   can_roll=False, target_mode="aura", area=20, cost_heroic=1,
                   applies_effects=[applies("Carisma: -1 em todas as rolagens", fx_type="bonus",
                                            fx_target="all", fx_value=-1, duration_mode="scene")]),
        ],
        img=IMG["social"],
    ),
    habilidade(
        "Carregador",
        "Anão das montanhas, anão das terras baixas, meio-orc, bárbaro, guardião e guerreiro.",
        "Sua Sobrecarga e sua Carga Máxima aumentam em 3 pontos.",
        "Sua Sobrecarga e sua Carga Máxima aumentam em 5 pontos, em vez de 3.",
        10, 30,
        img=IMG["corpo"],
    ),
    habilidade(
        "Cauda",
        "Infernal",
        "Você aprendeu a usar sua cauda como arma. Sua cauda é considerada uma arma natural, cujo ataque usa a Força e causa dano de Concussão +Nível.",
        "Quando você ataca com a sua cauda, você pode escolher agarrar o alvo em vez de causar dano. Quando o faz, você recebe 1D para essa rolagem de ataque. Você pode pagar 1 ponto heróico para tornar um ataque bem sucedido com cauda em um acerto crítico.",
        20, 40,
        activation="Ação (ataque)",
        actions=[action("Ataque de Cauda (dano = Concussão +Nível; ajuste o valor)",
                        roll_attr="forca", damage="1", damage_type="concussao",
                        defense_attr="esquiva", defense_attr2="bloqueio")],
        img=IMG["combate"],
    ),
    habilidade(
        "Combater às Cegas",
        "Monge e patrulheiro",
        "Mesmo que não possa enxergar, seus outros sentidos funcionam como se fossem seus olhos. Suas rolagens para localizar alvos que não possa ver recebem 1D.",
        "Você não é considerado indefeso quando é atacado por criaturas que não possa ver. Gastando 1 ponto heróico, você sabe a localização de todas as criaturas do combate que não estejam escondidas.",
        10, 30,
        img=IMG["pericia"],
    ),
    habilidade(
        "Combater sem Armadura",
        "Bárbaro e monge",
        "Quando você não estiver usando nenhuma armadura (escudos são permitidos), você recebe +1 em Esquiva e Bloqueio.",
        "Quando você não estiver usando nenhuma armadura (escudos são permitidos), você recebe Proteção igual a metade do seu Vigor.",
        10, 30,
        mode="active",
        effects=[
            effect("bonus", "esquiva", 1, level="B", label="Sem armadura: +1 Esquiva"),
            effect("bonus", "bloqueio", 1, level="B", label="Sem armadura: +1 Bloqueio"),
        ],
        img=IMG["corpo"],
    ),
    habilidade(
        "Companheiro Animal",
        "Druida e patrulheiro",
        "Você adestra uma criatura que tenha o traço Companheiro Animal, cujo Desafio seja igual ou menor ao seu nível. Você pode usar sua ação rápida para ordená-lo a usar sua Ação de Companheiro.",
        "Seu companheiro fica mais forte e recebe 1D em Força, Vigor ou Agilidade, à sua escolha. Você pode ordená-lo a usar sua Ação de Companheiro, usando sua ação livre, em vez de sua ação rápida.",
        20, 40,
        img=IMG["fera"],
    ),
    *[
        habilidade(
            f"Conhecimento ({area_c})",
            "Anão das montanhas, anão das terras baixas, alto elfo, elfo cinzento, elfo solar, elfo da floresta, gnomo da floresta, gnomo das profundezas, gnomo das rochas, meio-elfo, draconiano, entrópico, bárbaro, bardo, bruxo, clérigo, druida, mago, monge, paladino, patrulheiro.",
            f"Você recebe 1D nas rolagens de Mente relacionadas à área de {area_c}.",
            "Você pode gastar 1 ponto heróico para criar um “fato”, para resolver um caso ou para diminuir o grau de dificuldade de um teste de Mente relacionado à área em questão.",
            10, 30,
            img=IMG["pericia"],
        )
        for area_c in ["Arcano", "História", "Religião", "Natureza", "Guerra", "Ocultismo"]
    ],
    habilidade(
        "Contragolpe",
        "Bárbaro, guardião, guerreiro e monge",
        "Quando uma criatura erra um ataque contra você, você pode usar sua reação para imediatamente fazer um ataque contra ela.",
        "Quando uma criatura faz um ataque contra você (independente de errar ou acertar), você pode usar sua reação para imediatamente fazer um ataque contra ela.",
        20, 40,
        activation="Reação",
        img=IMG["combate"],
    ),
    habilidade(
        "Corredor",
        "Bárbaro e monge",
        "Seu Deslocamento aumenta em 3m.",
        "Seu Deslocamento aumenta em 5m (em vez de 3m). Adicionalmente, você recebe um bônus igual a metade do seu nível em rolagens para resistir e anular condições de Lento e Imobilizado.",
        10, 30,
        effects=[
            effect("stat", "deslocamento", 3, level="B", label="Corredor B: +3m Deslocamento"),
            effect("stat", "deslocamento", 2, level="A", label="Corredor A: +2m (total +5m)"),
        ],
        img=IMG["corpo"],
    ),
    habilidade(
        "Defletir Projéteis",
        "Monge",
        "Você recebe 1D em rolagens de Esquiva contra ataques à distância por meio de disparo de projéteis. Você pode apanhar os projéteis de ataques à distância dos quais você esquivou com sucesso com uma das mãos, se ela estiver vazia.",
        "Quando você aparar um projétil com a mão vazia, você pode usar sua reação para realizar imediatamente um ataque arremessando o projétil. O ataque usa uma rolagem de Agilidade, possui o mesmo dano básico do ataque bloqueado, alcance igual a 5m x Força e recebe os benefícios de uma arma de arremesso.",
        20, 40, prereq="Agilidade 4+",
        activation="Reação (nível A)",
        img=IMG["combate"],
    ),
    habilidade(
        "Desengajar",
        "Ladino e monge",
        "Você recebe 1D em rolagens de Esquiva contra reações de ataque, quando se move.",
        "Você pode gastar sua ação para se mover sem sofrer reações de ataque.",
        10, 30,
        img=IMG["corpo"],
    ),
    habilidade(
        "Empunhadura Dupla",
        "Guerreiro e patrulheiro",
        "Quando você ataca com duas armas, a penalidade nos ataques é de -2 (-1 para armas leves), em vez de -4.",
        "Quando você ataca com duas armas, você não sofre penalidades nos ataques.",
        20, 40,
        img=IMG["combate"],
    ),
    habilidade(
        "Energia Mágica Ampliada",
        "Celestial, draconiano e entrópico",
        "Seus pontos de magia aumentam em 2.",
        "Seus pontos de magia aumentam em 5 em vez de 2.",
        20, 40,
        effects=[
            effect("stat", "mp", 2, level="B", label="Energia Mágica Ampliada B: +2 PM"),
            effect("stat", "mp", 3, level="A", label="Energia Mágica Ampliada A: +3 PM (total +5)"),
        ],
        img=IMG["magia"],
    ),
    habilidade(
        "Escola Arcana",
        "Mago",
        "Escolha uma habilidade Palavra Arcana que você tenha aprendido. Você recebe um bônus em rolagens de Conjuração igual a metade do seu nível, para magias que sejam compostas por essa palavra.",
        "Resultados naturais 11 ou 12 em rolagens de Conjuração relacionadas à palavra arcana escolhida são considerados acertos críticos. Adicionalmente, magias compostas por essa palavra arcana, que causem dano, causarão 1 ponto de dano bruto adicional.",
        20, 40,
        img=IMG["magia"],
    ),
    habilidade(
        "Escolhido da Divindade",
        "Clérigo",
        "Você pode usar a Forma Divina dos Aspectos da sua divindade, a que você tem acesso.",
        "Você pode usar a Ira Divina dos Aspectos da sua divindade, a que você tem acesso.",
        20, 40, prereq="Primeiro Aspecto",
        img=IMG["social"],
    ),
    habilidade(
        "Especialista",
        "Gnomo da floresta, gnomo das rochas, bardo e ladino.",
        "Escolha uma habilidade que lhe conceda 1D em alguma ação ou tarefa fora de combate. Sempre que esse dado de melhoria for aplicado a uma rolagem, aplique 2D, em vez de 1D.",
        "Sempre que esse dado de melhoria for aplicado a uma rolagem, aplique 3D, em vez de 1D.",
        20, 40,
        img=IMG["pericia"],
    ),
    *[
        habilidade(
            f"Espírito Guardião ({animal})",
            "Bárbaro e druida",
            f"Gastando 1 ponto de magia, você recebe, por uma rodada, o benefício do espírito guardião: {beneficio}",
            "Gastando 2 pontos de magia (em vez de um ponto de magia), o benefício dura uma cena.",
            10, 30,
            mode="active",
            activation="Ação rápida",
            costs=[cost("mp", 1, "Invocar espírito (1 rodada; A: 2 PM = cena)")],
            effects=efeitos,
            img=IMG["fera"],
        )
        for animal, beneficio, efeitos in [
            ("Falcão", "1D em rolagens de Percepção.", [effect("dice", "percepcao", 1, label="Falcão: 1D Percepção")]),
            ("Urso", "3 pontos de sobrevida.", []),
            ("Tartaruga", "Proteção igual a metade do seu nível, contra corte, perfuração e concussão.", []),
            ("Carneiro", "Seus ataques bem sucedidos empurram o alvo 2m.", []),
            ("Leão", "1D em ataques corpo a corpo.", [effect("dice", "attack", 1, label="Leão: 1D em ataques")]),
            ("Cavalo", "Bônus de Deslocamento igual à sua Força.", []),
            ("Serpente", "1D em ações furtivas.", []),
            ("Lobo", "+2 no dano bruto se estiver adjacente a um aliado.", [effect("damage", "all", 2, label="Lobo: +2 dano (adjacente a aliado)")]),
            ("Búfalo", "Seus ataques bem sucedidos derrubam o alvo.", []),
            ("Carpa", "1D em Conjuração.", [effect("dice", "conjuracao", 1, label="Carpa: 1D Conjuração")]),
            ("Macaco", "1D em ataques à distância.", []),
            ("Cervo", "1D em interações sociais.", []),
        ]
    ],
    habilidade(
        "Espírito Inovador",
        "Jardins de Inverno",
        "Você pode gastar uma cena e fazer ajustes em um de seus equipamentos, modificando de forma que ele lhe conceda +1 nas rolagens de uso para o qual ele foi feito. No entanto, um resultado 6 ou menor na soma dos dois maiores dados de uma rolagem durante o uso danifica o equipamento, causando 3 pontos de dano à sua Dureza.",
        "O equipamento lhe concede +2 nas rolagens de uso para o qual ele foi feito. Uma rolagem 4 ou menos na soma dos dois maiores dados causa 2 pontos de dano em sua Dureza.",
        10, 30,
        img=IMG["pericia"],
    ),
    habilidade(
        "Estudos Místicos",
        "Bruxo",
        "Seus pontos de magia aumentam em 1 ponto para cada habilidade de Conhecimento que você possua em nível básico, e em 2 pontos para cada uma em nível avançado.",
        "Seu atributo de Conjuração aumenta em 1 ponto para cada habilidade de Conhecimento que você possua em nível avançado.",
        20, 40, prereq="Percepção 4+",
        img=IMG["magia"],
    ),
    habilidade(
        "Etiqueta",
        "Leão Dourado, cortesão, samurai",
        "Você recebe 1D em rolagens contra ser intimidado, ridicularizado, ofendido ou provocado.",
        "Se um personagem falhar em tentar te intimidar, ridicularizar, ofender ou provocar, você pode fazer imediatamente uma rolagem de Mente para fazer o mesmo de volta contra ele, com 1D adicional para essa rolagem.",
        10, 30,
        img=IMG["social"],
    ),
    habilidade(
        "Exímio Atirador",
        "Patrulheiro",
        "Se você não se mover no turno em que mirar, seu bônus no ataque por mirar aumenta para 2 pontos.",
        "Se você não se mover no turno em que mirar, seu bônus no ataque por mirar aumenta para 3 pontos.",
        20, 40,
        img=IMG["combate"],
    ),
    *[
        habilidade(
            f"Explorador ({terreno})",
            "Anão das montanhas, elfo da floresta, elfo das profundezas, gnomo da floresta, gnomo das profundezas, druida, patrulheiro, clérigo (Than, Kronox, Uru-haau, Neidar e Ruff)",
            f"Você recebe 1D em ações relacionadas ao terreno ({terreno.lower()}), enquanto estiver fora de combate.",
            f"Você recebe 1D em todas as rolagens em combate, enquanto estiver lutando no terreno em questão ({terreno.lower()}).",
            10, 30,
            img=IMG["fera"],
        )
        for terreno in ["Planícies", "Pântanos", "Colinas", "Florestas", "Aquáticos", "Glaciais", "Montanhas", "Desertos", "Cidades", "Subterrâneos"]
    ],
]
