# -*- coding: utf-8 -*-
"""Traços de raças e heranças. Fonte: Livro de Regras, Sessões 4 e 5."""
from builders import traco, effect, cost, action

IMG_RACA = "icons/svg/aura.svg"
IMG_HERANCA = "icons/svg/eye.svg"

TRACOS = [
    # ------------------------------ Raças -------------------------------
    traco("Visão no Escuro (10m)", "race",
          "Você enxerga no escuro até 10m.\n\nRaças: anões, alto elfo, elfo cinzento, elfo solar, elfo da floresta, gnomo da floresta, gnomo das rochas, meio-elfo, meio-orc; heranças celestial e infernal.",
          img=IMG_RACA),
    traco("Visão no Escuro (20m)", "race",
          "Você enxerga no escuro até 20m.\n\nRaças: elfo das profundezas, gnomo das profundezas, orc.",
          img=IMG_RACA),
    traco("Resistência Anã", "race",
          "Você recebe Proteção contra dano de veneno igual a metade do seu nível (arredondado para cima) e 1D em rolagens contra envenenamento.\n\nRaças: anão das montanhas, anão das terras baixas.",
          effects=[effect("rd", "all", 1, label="Resistência Anã: RD veneno (metade do Nível — ajuste)", damage_type="veneno")],
          img=IMG_RACA),
    traco("Filhos de Pálim", "race",
          "Você possui afinidade com minerais, recebendo 1D em todas as rolagens relacionadas a lidar com minerais.\n\nRaças: anão das montanhas, anão das terras baixas.",
          img=IMG_RACA),
    traco("Ancestral Faerian", "race",
          "Você recebe 1D em rolagens contra as condições Dominado, Enfeitiçado e Abalado. Adicionalmente, você não pode ser posto para dormir.\n\nRaças: alto elfo, elfo cinzento, elfo solar, elfo da floresta, elfo das profundezas, meio-elfo.",
          img=IMG_RACA),
    traco("Transe", "race",
          "Você não precisa dormir. Em vez disso, você descansa entrando em um transe de 4 horas.\n\nRaças: elfo cinzento, elfo solar, elfo da floresta, elfo das profundezas.",
          img=IMG_RACA),
    traco("Filhos de Kalael", "race",
          "Abençoado pelas deusas da floresta, da noite e da magia, seu criador recebeu grandes poderes mágicos. Parte desse poder foi passado para seu povo. Você recebe a habilidade Palavra Arcana (energio), sem ter que pagar por ela.\n\nRaça: elfo cinzento.",
          img=IMG_RACA),
    traco("Filhos de Auralia", "race",
          "Você pode viajar pelo plano da Selva Faérian para se locomover mais rápido quando necessário. Você possui Deslocamento de teletransporte 5m, mais 1m adicional para cada ponto em Mente. Cada vez que você teleporta, você perde 1 ponto de magia.\n\nRaça: elfo solar.",
          mode="active", costs=[cost("mp", 1, "Teleporte (5m + Mente)")],
          actions=[action("Teleporte Faérian (5m + Mente)", can_roll=False, target_mode="self",
                          movement={"kind": "teleport", "who": "self", "distance": 8,
                                    "ignoreWalls": True}, cost_mp=1)],
          img=IMG_RACA),
    traco("Filhos de Illain", "race",
          "Os mistérios das florestas são guardados pelo seu deus criador, Illain, protetor da natureza. Seus herdeiros receberam a capacidade de se manterem imperceptíveis em ambientes selvagens. Quando está em um ambiente selvagem (florestas, montanhas, desertos, pântanos...), você recebe 1D em Furtividade e em Esquiva.\n\nRaça: elfo da floresta.",
          img=IMG_RACA),
    traco("Prole de Mizra", "race",
          "Por causa da maldição lançada pela deusa da noite sobre seu povo, cada elfo das profundezas carrega um pedaço da umbra dentro de si. Você recebe a habilidade Palavra Arcana (tenebrae), sem pagar por ela.\n\nRaça: elfo das profundezas.",
          img=IMG_RACA),
    traco("Filhos de Agalard", "race",
          "Você recebe 1D em rolagens para se defender, evitar e resistir a magias.\n\nRaças: gnomo da floresta, gnomo das profundezas, gnomo das rochas.",
          img=IMG_RACA),
    traco("Ilusionista Natural", "race",
          "Você recebe a habilidade Palavra Arcana (iluzio) sem pagar por ela.\n\nRaça: gnomo da floresta.",
          img=IMG_RACA),
    traco("Camuflagem Natural", "race",
          "Você recebe 1D para se esconder em terreno rochoso.\n\nRaça: gnomo das profundezas.",
          img=IMG_RACA),
    traco("Inventor de Engenhocas", "race",
          "Você recebe 1D em rolagens para identificar, reparar e criar itens mecânicos.\n\nRaça: gnomo das rochas.",
          img=IMG_RACA),
    traco("Versátil", "race",
          "Você recebe 20 pontos de antecedentes adicionais na criação do personagem. Você pode gastar esses pontos adicionais para comprar habilidades de outras vocações ou raças como se fossem da sua lista (sem ter que pagar o dobro).\n\nRaça: humano.",
          img=IMG_RACA),
    traco("Sangue Aagn", "race",
          "Usando sua ação rápida, você pode gastar pontos de magia para recuperar pontos de vida. A cada 2 pontos de magia gastos, você recupera 1 ponto de vida.\n\nRaça: humano.",
          mode="active", costs=[cost("mp", 2, "Recupera 1 PV")],
          img=IMG_RACA),
    traco("Versatilidade dos Humanos", "race",
          "Você recebe 10 pontos de antecedentes adicionais na criação do personagem. Você pode gastar esses pontos adicionais para comprar habilidades de outras vocações ou raças como se fossem da sua lista (sem ter que pagar o dobro).\n\nRaça: meio-elfo.",
          img=IMG_RACA),
    traco("Sangue Ruim", "race",
          "Você recebe 1D nas rolagens para resistir a fome, sede e sono não mágicos. Você adicionalmente recebe 1D para resistir a ameaças climáticas como tempestades, nevascas ou calor intenso.\n\nRaça: meio-orc.",
          img=IMG_RACA),
    traco("Filhos de Grumbar", "race",
          "A cada cena que você passar sem combate, você recebe 1 ponto de Sede de Batalha que se acumula. Quando você entra em combate, você pode gastar esses pontos. Quando declarar um ataque, você pode gastar 1 ou mais pontos para receber um bônus para a rolagem de ataque igual à quantidade de pontos gastos.\n\nRaça: orc.",
          img=IMG_RACA),
    traco("Agilidade dos Pequeninos", "race",
          "Você pode se mover através de espaços de criaturas de tamanho maior que o seu.\n\nRaça: pequenino.",
          img=IMG_RACA),
    traco("Filhos de Ruff", "race",
          "Você pode gastar 1 ponto de magia para re-rolar um dado de qualquer rolagem.\n\nRaça: pequenino.",
          mode="active", costs=[cost("mp", 1, "Re-rolar um dado")],
          img=IMG_RACA),
    traco("Resistência dos Pequeninos", "race",
          "Você recebe 1D em rolagens contra venenos e doenças.\n\nRaça: pequenino.",
          img=IMG_RACA),
    # ------------------------------ Heranças ----------------------------
    traco("Ancestralidade Celestial", "heritage",
          "Você possui Proteção contra Frio, Fogo, Ácido e Veneno igual a metade do seu nível (arredondado para cima).\n\nHerança: celestial.",
          effects=[
              effect("rd", "all", 1, label="Ancestralidade Celestial: RD frio (metade do Nível — ajuste)", damage_type="frio"),
              effect("rd", "all", 1, label="Ancestralidade Celestial: RD fogo (metade do Nível — ajuste)", damage_type="fogo"),
              effect("rd", "all", 1, label="Ancestralidade Celestial: RD ácido (metade do Nível — ajuste)", damage_type="acido"),
              effect("rd", "all", 1, label="Ancestralidade Celestial: RD veneno (metade do Nível — ajuste)", damage_type="veneno"),
          ],
          img=IMG_HERANCA),
    traco("Fúria Draconiana", "heritage",
          "Se você perder mais da metade dos seus pontos de vida, você recebe +1 de bônus em seus ataques.\n\nHerança: draconiano.",
          img=IMG_HERANCA),
    traco("Sangue de Dragão", "heritage",
          "Quando você faz um descanso, você recupera 1 ponto de vida adicional.\n\nHerança: draconiano.",
          img=IMG_HERANCA),
    traco("Ancestralidade Draconiana", "heritage",
          "Você recebe Proteção igual a metade do seu nível (arredondado para cima) contra um tipo de dano, dependendo do tipo de dragão que você escolher para sua ancestralidade: Azul (Raio), Branco (Frio), Bronze (Raio), Cobre (Ácido), Latão (Fogo), Negro (Ácido), Ouro (Fogo), Prata (Frio), Verde (Veneno) ou Vermelho (Fogo).\n\nHerança: draconiano. Ajuste o efeito de RD abaixo para o tipo escolhido.",
          effects=[effect("rd", "all", 1, label="Ancestralidade Draconiana: RD do tipo escolhido (metade do Nível — ajuste)", damage_type="fogo")],
          img=IMG_HERANCA),
    traco("Resistência Draconiana", "heritage",
          "Seus pontos de vida máximos aumentam em 1.\n\nHerança: draconiano.",
          effects=[effect("stat", "hp", 1, label="Resistência Draconiana: +1 PV")],
          img=IMG_HERANCA),
    traco("Alma Entrópica", "heritage",
          "Após um descanso longo, role 1d6. Você recebe um dado de melhoria em um atributo de acordo com o resultado: 1 (Percepção), 2 (Vigor), 3 (Força), 4 (Agilidade), 5 (Mente) ou 6 (você escolhe).\n\nHerança: entrópico.",
          img=IMG_HERANCA),
    traco("Magia do Caos", "heritage",
          "Sempre que você conjurar uma magia, role 2d6. Se o resultado for menor que a quantidade de pontos de magia faltantes na sua reserva, sua Conjuração recebe um bônus igual a metade do seu nível e você rola 1d6 e confere o resultado:\n\n6 — A magia causa 1d6 de dano de energia, caso os alvos sejam inimigos, e cura 1d6 pontos de vida, caso os alvos sejam aliados. Você recebe uma condição positiva à escolha do narrador, até o fim da cena. 5 — A magia se repete em uma área ou alvo diferente, à sua escolha. 4 — A magia se repete em uma área ou alvo diferente, à escolha do narrador. 3 — A magia funciona normalmente. 2 — A magia falha e você recebe uma condição negativa até o fim da cena (Vigor anula), à escolha do narrador. 1 — Sua energia arcana explode e você recebe 1d6 pontos de dano bruto de energia.\n\nHerança: entrópico.",
          img=IMG_HERANCA),
    traco("Ancestralidade Infernal", "heritage",
          "Você possui Proteção contra fogo igual a metade do seu nível (arredondado para cima).\n\nHerança: infernal.",
          effects=[effect("rd", "all", 1, label="Ancestralidade Infernal: RD fogo (metade do Nível — ajuste)", damage_type="fogo")],
          img=IMG_HERANCA),
    traco("Caçada de Sangue", "heritage",
          "Você recebe 1D em seus ataques quando ataca criaturas que já estejam feridas.\n\nHerança: infernal.",
          img=IMG_HERANCA),
    traco("Vontade de Diamante", "heritage",
          "Você recebe um bônus de +1 em rolagens contra Abalado, Dominado, Enfeitiçado, Atordoado, Pasmo ou Dano Contínuo Psíquico para cada nível da habilidade Vontade de Ferro que você tiver aprendido.\n\nHerança: psiônico.",
          img=IMG_HERANCA),
    traco("Moldar Energia", "heritage",
          "Você pode usar seu movimento e gastar uma quantidade de pontos de magia para criar um objeto feito com a energia da sua mente, caso você seja bem sucedido em uma rolagem de Mente. A dificuldade para criar itens com peso 0 é Normal. A dificuldade aumenta em um nível a cada ponto de peso que o item a ser criado tiver acima de 0. O custo em pontos de magia é de 1 ponto + 1 ponto adicional por cada ponto de peso. Os itens funcionam normalmente, como qualquer outro, com exceção das armas, cujo dano é sempre de energia. O item dura até o fim da cena.\n\nHerança: psiônico.",
          mode="active", costs=[cost("mp", 1, "Criar objeto (peso 0; +1 PM por ponto de peso)")],
          actions=[action("Moldar Energia (Mente vs dificuldade)", roll_attr="mente",
                          vs_difficulty=True, fixed_difficulty=8, target_mode="none",
                          cost_mp=1)],
          img=IMG_HERANCA),
    traco("Presença Ardente", "heritage",
          "Você recebe um bônus igual a metade do seu nível em rolagens necessárias para o sucesso das habilidades Presença Aterradora, Provocar e Grito de Guerra.\n\nHerança: psiônico.",
          img=IMG_HERANCA),
]
