# -*- coding: utf-8 -*-
"""Magias de exemplo (Círculo Menor) — parte 1 (acida a lumo). Fonte: Sessão 11."""
from builders import magia, effect, cost, action, applies

IMG = "icons/svg/daze.svg"
IMG_DMG = "icons/svg/explosion.svg"
IMG_BUFF = "icons/svg/upgrade.svg"
IMG_HEAL = "icons/svg/heal.svg"


def _m(name, word, casting, target, area, rng, duration, desc, pecs,
       actions=None, effects=None, costs=None, mode="active", img=IMG):
    return magia(name, word, "Menor", casting, target, area, rng, duration,
                 desc, pecs, actions=actions, effects=effects,
                 costs=costs if costs is not None else [cost("mp", 1, "Círculo Menor")],
                 mode=mode, img=img)


MAGIAS_1 = [
    # ------------------------------- ACIDA ------------------------------
    _m("Rajada Ácida", "acida", "Ação", "Uma criatura ou objeto", "", "5m x Círculo x Nível", "",
       "Você pronuncia a palavra acida, e então sente um ardor em suas mãos. Uma esfera líquida surge flutuante, a partir da palma de sua mão. Você a aponta na direção de seu alvo. Uma rajada é disparada atingindo o inimigo e queimando-o com dano ácido.\n\nDano: Ácido +1 (Esquiva ou Bloqueio; bloqueios bem sucedidos causam 1 ponto de dano ao escudo).\n\nEfeito: Se o alvo sofrer dano, ele deve ser bem sucedido em uma rolagem de Dureza para não perder 1 ponto de Dureza de sua armadura e deve também ser bem sucedido em uma rolagem de Vigor oposta à sua Conjuração para não sofrer dano contínuo de ácido pelo resto da cena (Vigor anula).\n\nConhecimento (Natureza) concede +1 em Conjuração para esta conjuração.",
       "Dano: Ácido +2 (apenas Círculo Intermediário) (-). Dano: Ácido +3 (apenas Círculo Maior) (-). 1 ponto de dano adicional a um tipo de criatura (-1). A magia só funciona em um determinado tipo de terreno (+2). A magia não funciona contra um tipo de criatura ou raça (+1). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1). Alcance (Toque) (+2).",
       actions=[action("Rajada Ácida (Conjuração vs Esquiva/Bloqueio)",
                       roll_attr="conjuracao", damage="1", damage_type="acido",
                       defense_attr="esquiva", defense_attr2="bloqueio", rng=10, cost_mp=1,
                       applies_effects=[applies("Dano contínuo de ácido (Vigor anula)",
                                                fx_type="condition", fx_target="dano_continuo",
                                                duration_mode="scene", resist=True,
                                                resist_attr="vigor", tick_amount=1,
                                                tick_type="acido")])],
       img=IMG_DMG),
    _m("Corrosão", "acida", "Ação", "", "1m x Nível", "3m x Círculo x Nível", "",
       "Com um breve sussurro, você pronuncia a palavra acida, fazendo com que surja um nevoeiro corrosivo em uma área, queimando seus inimigos.\n\nEfeito: Todas as criaturas dentro da área devem fazer uma rolagem de Vigor oposta a Conjuração. Caso falhem, sofrerão dano contínuo de ácido pelo resto da cena (Vigor anula).\n\nConhecimento (Natureza) concede +1 em Conjuração para esta conjuração.",
       "A magia só funciona em um determinado tipo de terreno (+2). A magia não funciona contra um tipo de criatura ou raça (+1). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1). Alcance (Emanação), o conjurador não é afetado (+1). Todos os objetos dentro da área perdem 1 ponto de Dureza (-2).",
       actions=[action("Corrosão (Conjuração vs Vigor — área)",
                       roll_attr="conjuracao", target_mode="area", area=1, rng=6,
                       defense_attr="vigor", cost_mp=1,
                       applies_effects=[applies("Dano contínuo de ácido (Vigor anula)",
                                                fx_type="condition", fx_target="dano_continuo",
                                                duration_mode="scene", resist=True,
                                                resist_attr="vigor", tick_amount=1,
                                                tick_type="acido")])],
       img=IMG_DMG),
    # ------------------------------ AUGURADO ----------------------------
    _m("Detectar", "augurado", "Ação", "", "3m x Círculo x Nível", "Emanação", "",
       "Quando você pronuncia a palavra augurado, sua visão se aguça, fazendo com que seus alvos brilhem em meio ao cenário, mesmo estando atrás de maciças paredes.\n\nEfeito: Você detecta objetos ou criaturas escondidas. As criaturas devem ser bem sucedidas em uma rolagem de Mente oposta a Conjuração, para evitar serem detectadas. Caso falhem, a magia revela sua localização exata.\n\nAlerta concede +1 em Conjuração para esta conjuração.",
       "Pode detectar magia (-2). Detecta apenas um tipo de criatura (+2). Não detecta um tipo de criatura (+1). Detecta apenas criaturas com Corrupção 7 ou maior (+2). Detecta apenas criaturas com Corrupção 3 ou menor (+2). Detecta apenas objetos de um tipo de material (+2). Não detecta um tipo de material (-1). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Detectar (Conjuração vs Mente — emanação)",
                       roll_attr="conjuracao", target_mode="aura", area=6,
                       defense_attr="mente", cost_mp=1)]),
    _m("Revelar Passado", "augurado", "Ação", "Uma criatura ou objeto", "", "Toque", "",
       "Você toca o seu alvo e pronuncia a palavra augurado, mergulhando na mente dele e viajando através de suas memórias. Durante essas visões, você e seu alvo ficam em transe, vivenciando o passado.\n\nEfeito: Permite que o conjurador veja cenas do passado do alvo ao tocá-lo, caso o alvo falhe em uma rolagem de Mente oposta a Conjuração. É possível acessar memórias de uma quantidade de dias atrás igual ao seu atributo de Conjuração. O conjurador e o alvo ficam atordoados por uma rodada.\n\nConhecimento (História) concede +1 em Conjuração para esta conjuração.",
       "Meses, em vez de dias (apenas Círculo Intermediário ou Maior) (-2). Anos, em vez de dias (apenas Círculo Maior) (-4). O conjurador sofre 1 ponto de dano quando conjura (+1). O conjurador não fica atordoado (-2). O alvo não fica atordoado (+1). O alvo sabe o que o conjurador está vendo (+1). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Revelar Passado (Conjuração vs Mente — toque)",
                       roll_attr="conjuracao", defense_attr="mente", cost_mp=1,
                       applies_effects=[applies("Atordoado (1 rodada)", fx_type="condition",
                                                fx_target="atordoado", duration_mode="rounds",
                                                duration_rounds=1)])]),
    _m("Visão Futura", "augurado", "Ação", "Conjurador", "", "", "",
       "Você sussurra a palavra augurado para si mesmo, fazendo com que sua consciência viaje através do tempo, mostrando a você turvas imagens das ameaças que irão prejudicá-lo, auxiliando-o a tomar um melhor caminho.\n\nEfeito: Você pode re-rolar apenas uma vez todos os dados das suas próximas três rolagens. Você ainda pode gastar pontos heróicos para re-rolar qualquer uma delas normalmente. Você deve ficar com o segundo resultado, caso o faça.\n\nConhecimento (Religião) concede +1 em Conjuração para esta conjuração.",
       "Cinco rolagens, em vez de três (apenas Círculo Intermediário ou Maior) (-6). Sete rolagens, em vez de três (apenas Círculo Maior) (-8). O conjurador sofre 1 ponto de dano quando conjura (+1). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       img=IMG_BUFF),
    # ------------------------------- CARMO ------------------------------
    _m("Causar Medo", "carmo", "Ação", "", "Nível", "Emanação", "Uma cena",
       "Você sussurra a palavra carmo enquanto seu olhar brilha vermelho. Em seguida, você entra na mente de cada uma das criaturas ao seu redor, preenchendo-as de medo e desespero.\n\nEfeito: Todas as criaturas dentro da emanação devem ser bem sucedidas em uma rolagem de Mente oposta a Conjuração, para não ficarem abaladas até o fim da cena (Mente anula). Uma mesma criatura não pode ser afetada por essa magia mais de uma vez no mesmo dia.\n\nCarisma concede +1 em Conjuração para esta conjuração.",
       "Só afeta um determinado tipo de criatura (+2). Não afeta um determinado tipo de criatura (+1). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1). Alvos ficam também imobilizados até o fim da cena (Mente anula) (-2). Alvos ficam também paralisados até o fim da cena (Mente anula) (-4).",
       actions=[action("Causar Medo (Conjuração vs Mente — emanação)",
                       roll_attr="conjuracao", target_mode="aura", area=3,
                       defense_attr="mente", cost_mp=1,
                       applies_effects=[applies("Abalado (Mente anula)", fx_type="condition",
                                                fx_target="abalado", duration_mode="scene",
                                                resist=True, resist_attr="mente")])]),
    _m("Esvaziar a Mente", "carmo", "Ação", "Uma criatura", "", "3m x Círculo x Nível", "Uma cena",
       "Quando pronuncia a palavra carmo, você entra na mente de seu alvo e o coloca em um estado de inconsciência.\n\nEfeito: O alvo deve ser bem sucedido em uma rolagem de Mente oposta a Conjuração, para não ficar pasmo até o fim da cena (Mente anula). Uma mesma criatura não pode ser afetada por essa magia mais de uma vez no mesmo dia.\n\nCarisma concede +1 em Conjuração para esta conjuração.",
       "O alvo fica atordoado, em vez de pasmo (apenas Círculo Maior) (-4). Alcance (Emanação) e Área (3m) (-5). Alcance (Toque) (+2). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Esvaziar a Mente (Conjuração vs Mente)",
                       roll_attr="conjuracao", defense_attr="mente", rng=6, cost_mp=1,
                       applies_effects=[applies("Pasmo (Mente anula)", fx_type="condition",
                                                fx_target="pasmo", duration_mode="scene",
                                                resist=True, resist_attr="mente")])]),
    _m("Controlar Criatura", "carmo", "Ação", "Uma criatura", "", "3m x Círculo x Nível",
       "Sustentável — Ação Rápida",
       "Você pronuncia a palavra carmo em tom claro, enquanto mira sua visão em seu alvo, fazendo com que o mesmo entre em um torpor no qual segue suas ordens.\n\nEfeito: O alvo deve ser bem sucedido em uma rolagem de Mente oposta a Conjuração, para não ficar dominado pelo conjurador pela duração da magia (Mente anula). Uma mesma criatura não pode ser afetada por essa magia mais de uma vez no mesmo dia.\n\nCarisma concede +1 em Conjuração para esta conjuração.",
       "Alcance (Emanação) e Área (3m) (-5). Alcance (Toque) (+2). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Controlar Criatura (Conjuração vs Mente)",
                       roll_attr="conjuracao", defense_attr="mente", rng=6, cost_mp=1,
                       applies_effects=[applies("Dominado (Mente anula)", fx_type="condition",
                                                fx_target="dominado", duration_mode="scene",
                                                resist=True, resist_attr="mente")])]),
    # ------------------------------- DEVENA -----------------------------
    _m("Controlar a Terra", "devena", "Ação", "Um espaço", "", "Nível x Círculo",
       "Sustentável — Ação Rápida",
       "Conforme você pronuncia a palavra arcana devena, o solo se move assumindo uma forma diferente conforme sua vontade.\n\nEfeito: Você faz com que o chão de terra se mova num espaço alvo dentro do alcance e assuma uma das formas na lista abaixo. Se o espaço alvo escolhido estiver ocupado por alguma criatura, esta deve ser bem sucedida em uma rolagem de Agilidade oposta a Conjuração para não cair no chão.\n\nMuralha de Pedra — um muro de pedra se ergue do chão. Ele ocupa uma quantidade de metros em linha reta igual ao seu atributo de Mente + Nível, e possui altura igual a seu Nível +1 em metros. Pilar de Pedra — um pilar alto de pedra se ergue do chão. Ele possui diâmetro igual ao seu Nível em metros; a altura dele é igual ao seu atributo de Mente + o dobro do seu Nível. Esfera de Pedra — uma esfera grande de pedra se forma a partir do chão. Ela possui diâmetro igual ao seu Nível em metros.\n\nConhecimento (Natureza) concede +1 em Conjuração para esta conjuração.",
       "Pode movê-la depois de criada, usando sua ação, uma distância igual ao alcance (apenas Círculo Intermediário ou Maior) (-4). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Controlar a Terra (Conjuração vs Agilidade se ocupado)",
                       roll_attr="conjuracao", defense_attr="agilidade", rng=4, cost_mp=1,
                       applies_effects=[applies("Caído", fx_type="condition", fx_target="caido",
                                                duration_mode="rounds", duration_rounds=1)])]),
    _m("Força da Natureza", "devena", "Ação", "", "2m x Nível", "Emanação",
       "Sustentável — Ação Rápida",
       "Conforme você pronuncia a palavra arcana devena e toca o chão, a natureza à sua volta responde ao seu comando, criando uma área de ameaça aos seus inimigos.\n\nEfeito: Você cria um efeito diferente dentro da área, de acordo com o terreno natural em que se encontra. O conjurador é imune ao efeito da magia.\n\nPlanícies (Ventania) — 1 dano bruto sônico e Lento até deixar a área. Montanhas (Terremoto) — 1 dano bruto de concussão e Caído. Colinas (Tempestade) — 1 dano bruto de raio e Surdo até deixar a área. Florestas (Nevoeiro) — 1 dano bruto de ácido e Cego até deixar a área. Pântanos (Vinhas) — 1 dano bruto de veneno e Lento até deixar a área. Desertos (Ondas de Calor) — 1 dano bruto de fogo e Enfraquecido até deixar a área. Glacial (Nevasca) — 1 dano bruto de frio e Lento até deixar a área. Subterrâneos (Vácuo) — 1 dano final e Emudecido até deixar a área. (Criaturas que entrarem ou iniciarem seus turnos dentro da área sofrem o efeito.)\n\nConhecimento (Natureza) concede +1 em Conjuração para esta conjuração.",
       "Adiciona um segundo efeito, de outro terreno (apenas Círculo Intermediário ou Maior) (-4). Adiciona dois efeitos de outros terrenos (apenas Círculo Maior) (-6). O terreno afeta você (+2). Só funciona em um tipo de terreno (+2). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Força da Natureza (área persistente, dano por terreno)",
                       roll_attr="conjuracao", target_mode="area", area=4, cost_mp=1,
                       damage="1", damage_type="concussao",
                       persist_area=True, persist_rounds=0, persist_trigger="both")],
       img=IMG_DMG),
    _m("Invocar Animais", "devena", "Ação", "Um espaço vazio", "", "Nível x Círculo",
       "Sustentável — Ação Rápida",
       "Você pronuncia a palavra arcana devena enquanto mentaliza uma fera se materializando no lugar onde você está focando sua visão, trazendo um animal de um lugar distante para auxiliá-lo.\n\nEfeito: Você invoca uma criatura do tipo fera pequena, com Desafio igual ao dobro do seu Nível ou menos, no espaço alvo. A criatura é amigável a você e seus aliados, e hostil a seus inimigos, atacando-os em seu turno.\n\nConhecimento (Natureza) concede +1 em Conjuração para esta conjuração.",
       "Invoca criatura média (apenas Círculo Intermediário ou Maior) (-1). Invoca criatura grande (apenas Círculo Maior) (-3). Desafio 3 + seu nível, ou menos (apenas Círculo Intermediário ou Maior) (-4). Desafio 6 + seu nível ou menos (apenas Círculo Maior) (-6). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1)."),
    _m("Invocar Plantas", "devena", "Ação", "Um espaço vazio", "", "Nível x Círculo",
       "Sustentável — Ação Rápida",
       "Você pronuncia a palavra devena, fazendo com que cresça uma planta carnívora em um espaço vazio, a qual ao fim da invocação dá frutos.\n\nEfeito: Você invoca uma criatura do tipo planta, pequena, no espaço alvo, com Desafio igual ao seu nível ou menos. A planta é amigável a você e seus aliados e hostil a seus inimigos, atacando-os, se possível. A planta invocada concede uma quantidade de frutos no final da invocação, igual a seu atributo de Mente. Esses frutos podem ser medicinais ou venenosos (você escolhe quando invocar). Frutos medicinais curam 1 ponto de vida quando ingeridos (e contam como uma refeição); frutos venenosos causam 1 ponto de dano bruto de veneno quando ingeridos.\n\nConhecimento (Natureza) concede +1 em Conjuração para esta conjuração.",
       "Invoca criatura média (apenas Círculo Intermediário ou Maior) (-1). Invoca criatura grande (apenas Círculo Maior) (-3). Desafio 3 + seu nível, ou menos (apenas Círculo Intermediário ou Maior) (-4). Desafio 6 + seu nível ou menos (apenas Círculo Maior) (-6). Os frutos curam/causam 2 pontos de dano (apenas Círculo Intermediário ou Maior) (-2). Os frutos curam/causam 3 pontos de dano (apenas Círculo Maior) (-4). O conjurador perde 1 ponto de vida quando a conjura (+2). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1)."),
    # ------------------------------- ENERGIO ----------------------------
    _m("Aura Arcana", "energio", "Ação", "", "Nível x Círculo", "Aura",
       "Sustentação — Ação Rápida",
       "Conforme você pronuncia a palavra energio, mentalizando um mapa arcano, você cria uma aura de energia em torno de si, que fere qualquer um que se aproxime de você.\n\nEfeito: Você emana uma aura de energia centrada em si mesmo. Todas as criaturas que entrarem ou iniciarem seus turnos dentro dela sofrem 1 ponto de dano de energia.\n\nConhecimento (Arcano) concede +1 em Conjuração para esta conjuração.",
       "A aura causa 2 pontos de dano de energia (apenas Círculo Intermediário) (-). A aura causa 3 pontos de dano de energia (apenas Círculo Maior) (-). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Aura Arcana (dano de energia na aura)",
                       can_roll=False, target_mode="aura", area=3, cost_mp=1,
                       damage="1", damage_type="energia",
                       persist_area=True, persist_rounds=0, persist_trigger="both")],
       img=IMG_DMG),
    _m("Raio Arcano", "energio", "Ação", "Uma criatura ou objeto", "", "5m x Nível x Círculo", "",
       "Enquanto pronuncia energio, você traça mentalmente um trajeto que leva a explosão de energia criada na palma de suas mãos até o seu alvo.\n\nDano: Energia +2 (Esquiva ou Bloqueio).\n\nConhecimento (Arcano) concede +1 em Conjuração para esta conjuração.",
       "Dano: Energia +3 (apenas Círculo Intermediário) (-). Dano: Energia +4 (apenas Círculo Maior) (-). Alcance (Toque) (+2). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1). A magia só funciona contra um tipo de criatura ou raça (+2). A magia não funciona contra um tipo de criatura ou raça (+1).",
       actions=[action("Raio Arcano (Conjuração vs Esquiva/Bloqueio)",
                       roll_attr="conjuracao", damage="2", damage_type="energia",
                       defense_attr="esquiva", defense_attr2="bloqueio", rng=10, cost_mp=1)],
       img=IMG_DMG),
    # ------------------------------- EXITIUM ----------------------------
    _m("Explodir", "exitium", "Ação", "", "1m x Nível", "3m x Círculo x Nível", "",
       "Gritando a palavra exitium, você cria uma explosão em uma área, de pura energia destrutiva, ferindo seus inimigos.\n\nDano: Dano Final de Energia 1 (Esquiva, não escalável).\n\nEfeitos: Você sofre 1 ponto de dano final (não é possível evitar esse dano de qualquer forma).\n\nConhecimento (Arcano) concede +1 em Conjuração para esta conjuração.",
       "Dano Final de Energia 2 (apenas Círculo Intermediário) (-). Dano Final de Energia 3 (apenas Círculo Maior) (-). O dano final sofrido pelo conjurador aumenta para 2 (+2). Alcance (Emanação) e Área (2m) (+1). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Explodir (dano final de energia; você sofre 1 de dano final)",
                       roll_attr="conjuracao", target_mode="area", area=1, rng=6,
                       damage="1", damage_type="final", scaling_damage=False,
                       defense_attr="esquiva", cost_mp=1, cost_hp=1)],
       img=IMG_DMG),
    _m("Míssil Mágico", "exitium", "Ação", "Uma criatura ou objeto", "", "5m x Círculo x Nível", "",
       "Pronunciando a palavra exitium, você lança da ponta de seu dedo um míssil de energia arcana contra seu inimigo, que se choca contra ele inevitavelmente.\n\nDano: Energia 1 (Indefensável, não escalonável).\n\nConhecimento (Arcano) concede +1 em Conjuração para esta conjuração.",
       "Dano: Energia 2 (apenas Círculo Intermediário) (-). Dano: Energia 3 (apenas Círculo Maior) (-). 1 míssil adicional (-6). 2 mísseis adicionais (-8). O conjurador sofre 1 ponto de dano ao conjurar esta magia (+2). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Míssil Mágico (acerta automaticamente)",
                       can_roll=False, damage="1", damage_type="energia",
                       scaling_damage=False, rng=10, cost_mp=1)],
       img=IMG_DMG),
    # ------------------------------- FORJURI ----------------------------
    _m("Armadura Arcana", "forjuri", "Ação", "Conjurador", "", "Toque", "Dia",
       "Pronunciando a palavra forjuri e tocando o alvo, você fornece ao mesmo uma armadura de energia arcana, que cobre todo o seu corpo.\n\nEfeitos: O alvo recebe Proteção 1 contra dano de Perfuração, Corte e Concussão. Esta proteção não se acumula com a proteção das armaduras.\n\nOfícios concede +1 em Conjuração para esta conjuração. Conhecimento (Guerra) concede +1 em Conjuração para esta conjuração.",
       "A Proteção aumenta para 2 (apenas Círculo Intermediário) (-). A Proteção aumenta para 3 (apenas Círculo Maior) (-). Outro tipo de dano (+2). Um tipo de dano adicional (-1). Alvo muda de Conjurador para Criatura (apenas Círculo Maior) (-4). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       effects=[
           effect("rd", "all", 1, label="Armadura Arcana: Proteção 1 (corte)", damage_type="corte"),
           effect("rd", "all", 1, label="Armadura Arcana: Proteção 1 (perfuração)", damage_type="perfuracao"),
           effect("rd", "all", 1, label="Armadura Arcana: Proteção 1 (concussão)", damage_type="concussao"),
       ],
       img=IMG_BUFF),
    _m("Escudo Arcano", "forjuri", "Ação", "Conjurador", "", "Toque",
       "Sustentável — Ação Rápida",
       "Tocando seu alvo enquanto pronuncia a palavra arcana forjuri, você faz com que surja um escudo de energia arcana flutuante girando em torno do mesmo.\n\nEfeitos: O alvo recebe +1 nas rolagens de Bloqueio e é considerado como se empunhasse um escudo, mas sem ocupar as mãos. Suas rolagens de Bloqueio com esse escudo usam Mente em vez de Força.\n\nOfícios concede +1 em Conjuração para esta conjuração. Conhecimento (Guerra) concede +1 em Conjuração para esta conjuração.",
       "Deflexão reduz 2 pontos de dano (apenas Círculo Intermediário) (-). Deflexão reduz 3 pontos de dano (apenas Círculo Maior) (-). Bloqueia magias esquiváveis (apenas Círculo Maior) (-4). Alvo muda de Conjurador para Criatura (apenas Círculo Maior) (-4). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       effects=[effect("bonus", "bloqueio", 1, label="Escudo Arcano: +1 Bloqueio")],
       img=IMG_BUFF),
    _m("Barreira Arcana", "forjuri", "Ação", "", "1m x Nível", "Emanação",
       "Sustentável — Ação",
       "Pronunciando a palavra forjuri, você cria em torno de si uma barreira que repele seus inimigos e os mantém afastados, protegendo você e seus aliados.\n\nEfeitos: Você conjura uma barreira do tamanho da área, em torno de si. Todos os seus inimigos dentro da barreira devem ser bem sucedidos em uma rolagem de Mente oposta a Conjuração, a cada rodada no começo do seu turno, ou serão empurrados para fora da barreira. Inimigos fora da barreira que tentem entrar deverão ser bem sucedidos em uma rolagem de Mente oposta a Conjuração, ou terão seu movimento finalizado adjacente à barreira. Ataques e magias que tenham você ou seus aliados dentro da barreira como alvos devem superar sua rolagem de Conjuração. Magias que afetem áreas devem superar sua rolagem de Conjuração para que afetem espaços dentro da barreira. Caso contrário, o ataque falha. Caso supere, o alvo do ataque deve se defender normalmente. Metamagias acrescentadas a esta magia base que afetarem você também afetam seus aliados dentro da barreira; as que afetariam alvos da magia afetam os inimigos dentro da barreira.\n\nConhecimento (Religião) concede +1 em Conjuração para esta conjuração. Conhecimento (Guerra) concede +1 em Conjuração para esta conjuração.",
       "Inimigos que falharem na rolagem de Mente oposta a Conjuração ficam pasmos até o fim da cena (Mente anula) (apenas Círculo Intermediário ou Maior) (-4). Inimigos que falharem na rolagem de Mente oposta a Conjuração ficam atordoados até o fim da cena (Mente anula) (apenas Círculo Maior) (-6). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1). Sustentável — Movimento (apenas Círculo Intermediário ou Maior) (-2). Sustentável — Ação Rápida (apenas Círculo Maior) (-4). Alcance (Aura) (apenas Círculo Maior) (-4).",
       actions=[action("Barreira Arcana (Conjuração vs Mente — emanação)",
                       roll_attr="conjuracao", target_mode="aura", area=2,
                       defense_attr="mente", cost_mp=1,
                       persist_area=True, persist_rounds=0, persist_trigger="start")],
       img=IMG_BUFF),
    # ------------------------------- FULGUR -----------------------------
    _m("Relâmpago", "fulgur", "Ação", "Uma criatura ou objeto", "", "5m x Círculo x Nível", "",
       "Você pronuncia a palavra fulgur, fazendo com que um raio desça do céu e atinja seu alvo.\n\nDano: Raio +1 (Esquiva).\n\nEfeitos: Se o alvo sofrer dano, todas as criaturas adjacentes a ele sofrem 1 ponto de dano bruto de raio (+1 adicional para cada círculo acima do Menor).\n\nConhecimento (Natureza) concede +1 em Conjuração para esta conjuração.",
       "Dano: Raio +2 (apenas Círculo Intermediário) (-). Dano: Raio +3 (apenas Círculo Maior) (-). Aumentar a distância entre os alvos secundários e o primário em 1m (-2). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Relâmpago (Conjuração vs Esquiva; adjacentes sofrem 1 de raio)",
                       roll_attr="conjuracao", damage="1", damage_type="raio",
                       defense_attr="esquiva", rng=10, cost_mp=1)],
       img=IMG_DMG),
    _m("Toque Chocante", "fulgur", "Ação", "Uma criatura", "", "Toque", "",
       "Sussurrando a palavra fulgur, você toca seu alvo, transformando a energia arcana em suas mãos em um choque que paralisa seu alvo.\n\nDano: Raio +1 (Esquiva).\n\nEfeitos: Se o alvo sofrer dano, ele deve ser bem sucedido em uma rolagem de Vigor oposta a Conjuração, ou ele ficará imobilizado pelo resto da cena (Vigor anula).\n\nConhecimento (Arcano) concede +1 em Conjuração para esta conjuração.",
       "O alvo fica paralisado até o fim da cena (Vigor anula) (-2). O alvo sofre dano contínuo de raio até o fim da cena (Vigor anula) (-4). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Toque Chocante (Conjuração vs Esquiva — toque)",
                       roll_attr="conjuracao", damage="1", damage_type="raio",
                       defense_attr="esquiva", cost_mp=1,
                       applies_effects=[applies("Imobilizado (Vigor anula)", fx_type="condition",
                                                fx_target="imobilizado", duration_mode="scene",
                                                resist=True, resist_attr="vigor")])],
       img=IMG_DMG),
    # ------------------------------- GLACIOS ----------------------------
    _m("Raio de Gelo", "glacios", "Ação", "Uma criatura ou objeto", "", "5m x Círculo x Nível", "",
       "Conforme você pronuncia a palavra glacios, a ponta de seu dedo indicador sofre uma queda de temperatura gigantesca, até criar uma centelha gélida o suficiente para que você possa lançar este raio gelado em seu inimigo.\n\nDano: Frio +1 (Esquiva).\n\nEfeitos: Se o alvo sofrer dano, ele deve ser bem sucedido em uma rolagem de Vigor oposta a Conjuração, ou ficará lento até o fim da cena (Vigor anula).\n\nConhecimento (Arcano) concede +1 em Conjuração para esta conjuração.",
       "Dano: Frio +2 (apenas Círculo Intermediário) (-). Dano: Frio +3 (apenas Círculo Maior) (-). O alvo sofre dano contínuo de frio até o fim da cena (Vigor anula) (-4). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Raio de Gelo (Conjuração vs Esquiva)",
                       roll_attr="conjuracao", damage="1", damage_type="frio",
                       defense_attr="esquiva", rng=10, cost_mp=1,
                       applies_effects=[applies("Lento (Vigor anula)", fx_type="condition",
                                                fx_target="lento", duration_mode="scene",
                                                resist=True, resist_attr="vigor")])],
       img=IMG_DMG),
    _m("Área Congelada", "glacios", "Ação", "", "1m x Nível", "3m x Círculo x Nível", "",
       "Você pronuncia a palavra glacios enquanto seus olhos miram em uma direção, baixando a temperatura do lugar alvo, congelando o chão até que o gelo cresça e prenda as criaturas no local.\n\nDano: Frio +1 (Esquiva).\n\nEfeitos: Se um alvo sofrer dano, ele deve ser bem sucedido em uma rolagem de Agilidade oposta a Conjuração, ou ficará lento até o fim da cena (Força anula).\n\nConhecimento (Natureza) concede +1 em Conjuração para esta conjuração.",
       "Cada alvo fica imobilizado até o fim da cena (apenas Círculo Intermediário ou Maior) (Vigor anula) (-2). Cada alvo fica paralisado até o fim da cena (apenas Círculo Maior) (Vigor anula) (-4). Os alvos sofrem dano contínuo de frio até o fim da cena (apenas Círculo Maior) (Vigor anula) (-4). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Área Congelada (Conjuração vs Esquiva — área)",
                       roll_attr="conjuracao", target_mode="area", area=2, rng=6,
                       damage="1", damage_type="frio", defense_attr="esquiva", cost_mp=1,
                       applies_effects=[applies("Lento (Força anula)", fx_type="condition",
                                                fx_target="lento", duration_mode="scene",
                                                resist=True, resist_attr="forca")])],
       img=IMG_DMG),
    # -------------------------------- IGNIS -----------------------------
    _m("Esfera Ígnea", "ignis", "Ação", "Uma criatura ou objeto", "", "5m x Círculo x Nível", "",
       "Você pronuncia a palavra ignis, enquanto desenha a runa da centelha em sua mente. O círculo de conjuração, que se forma nas pontas de seus dedos, logo dá lugar a uma esfera ardente de chamas intensas. Com apenas um movimento da mão, você a arremessa em seu desafortunado inimigo.\n\nDano: Fogo +1 (Esquiva).\n\nEfeitos: Se o alvo sofrer dano, ele deve ser bem sucedido em uma rolagem de Agilidade oposta a Conjuração, ou sofrerá dano contínuo de fogo até o fim da cena (Agilidade anula).\n\nConhecimento (Arcano) concede +1 em Conjuração para esta conjuração.",
       "Dano: Fogo +2 (apenas Círculo Intermediário) (-). Dano: Fogo +3 (apenas Círculo Maior) (-). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Esfera Ígnea (Conjuração vs Esquiva)",
                       roll_attr="conjuracao", damage="1", damage_type="fogo",
                       defense_attr="esquiva", rng=10, cost_mp=1,
                       applies_effects=[applies("Dano contínuo de fogo (Agilidade anula)",
                                                fx_type="condition", fx_target="dano_continuo",
                                                duration_mode="scene", resist=True,
                                                resist_attr="agilidade", tick_amount=1,
                                                tick_type="fogo")])],
       img=IMG_DMG),
    _m("Combustão", "ignis", "Ação", "", "1m x Nível", "3m x Círculo x Nível", "",
       "Através da pronúncia da palavra ignis, você faz com que a temperatura de uma pequena área suba a ponto de fazer com que as criaturas dentro dela entrem em combustão.\n\nEfeitos: Todas as criaturas dentro da área devem ser bem sucedidas em uma rolagem de Vigor oposta a Conjuração, ou sofrerão dano contínuo de fogo pelo resto da cena (Vigor anula).\n\nConhecimento (Arcano) concede +1 em Conjuração para esta conjuração.",
       "Os alvos ficam exaustos até o fim da cena (Vigor anula) (apenas Círculo Intermediário ou Maior) (-2). Criaturas atingidas perdem todos os dados de melhoria em ações físicas (apenas Círculo Maior) (-6). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Combustão (Conjuração vs Vigor — área)",
                       roll_attr="conjuracao", target_mode="area", area=2, rng=6,
                       defense_attr="vigor", cost_mp=1,
                       applies_effects=[applies("Dano contínuo de fogo (Vigor anula)",
                                                fx_type="condition", fx_target="dano_continuo",
                                                duration_mode="scene", resist=True,
                                                resist_attr="vigor", tick_amount=1,
                                                tick_type="fogo")])],
       img=IMG_DMG),
    # -------------------------------- ILUZIO ----------------------------
    _m("Imagem Ilusória", "iluzio", "Ação", "Um espaço vazio", "", "5m x Círculo x Nível",
       "Sustentação — Ação Rápida",
       "Pronunciando a palavra iluzio, você se concentra em manipular a luz, moldando sua ideia de imagem em algo visível.\n\nEfeitos: Cria uma imagem média de uma criatura ou objeto no espaço alvo. A imagem não se move, não tem cheiro, não emite nenhum tipo de som e é intangível. Todos que interagirem com a ilusão (conversar, tocar, atacar...) deverão ser bem sucedidos em uma rolagem de Percepção oposta a Conjuração, para notar que se trata de uma ilusão.\n\nCarisma concede +1 em Conjuração para esta conjuração.",
       "A imagem tem cheiro (-4). A imagem se movimenta (-4). A imagem possui tangibilidade (-4). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1)."),
    _m("Invisibilidade", "iluzio", "Ação", "Conjurador", "", "", "Uma cena",
       "Sussurrando a palavra iluzio, você consegue manipular a luz de forma a ocultar a sua imagem da visão dos que estão ao redor.\n\nEfeitos: O alvo se torna invisível pelo resto da cena. No entanto, ele cancela este efeito se realizar um ataque ou se mover.\n\nFurtividade concede +1 em Conjuração para esta conjuração.",
       "O alvo pode se mover sem cancelar o efeito (apenas Círculo Intermediário ou Maior) (-4). O alvo pode se mover ou atacar sem cancelar o efeito (apenas Círculo Maior) (-8). Só fica invisível para um tipo de criatura (+1). Só um tipo de criatura pode vê-lo (+2). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Invisibilidade (aplica em si mesmo)",
                       can_roll=False, target_mode="self", include_self=True, cost_mp=1,
                       applies_effects=[applies("Invisível (cancela ao atacar ou mover)",
                                                fx_type="condition", fx_target="invisivel",
                                                duration_mode="scene")])],
       img=IMG_BUFF),
    _m("Visão Aterradora", "iluzio", "Ação", "Uma criatura que possua visão", "",
       "3m x Círculo x Nível", "",
       "Pronunciando iluzio, você consegue criar, diante dos olhos de seu alvo, visões horripilantes que o deixam extremamente abalado.\n\nDano: Psíquico +0 (Percepção).\n\nEfeitos: Caso o alvo sofra dano, ele deve ser bem sucedido em uma rolagem de Percepção, para não ficar abalado até o fim da cena (Percepção anula).\n\nCarisma concede +1 em Conjuração para esta conjuração.",
       "Dano: Psíquico +1 (apenas Círculo Intermediário) (-). Dano: Psíquico +2 (apenas Círculo Maior) (-). O alvo fica inconsciente até o fim da cena (Mente anula) (-5). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Visão Aterradora (Conjuração vs Percepção)",
                       roll_attr="conjuracao", damage="0", damage_type="psiquico",
                       defense_attr="percepcao", rng=6, cost_mp=1,
                       applies_effects=[applies("Abalado (Percepção anula)", fx_type="condition",
                                                fx_target="abalado", duration_mode="scene",
                                                resist=True, resist_attr="percepcao")])],
       img=IMG_DMG),
    # -------------------------------- INANIS ----------------------------
    _m("Cancelar Magia", "inanis", "Ação",
       "Uma área de efeito, um item mágico, uma criatura afetada", "", "5m x Círculo x Nível", "",
       "Você pronuncia a palavra inanis, enquanto um efeito mágico visível se torna seu foco visual. O seu poder arcano segue como uma onda neutralizando a magia.\n\nEfeitos: Esta magia anula permanentemente uma área de efeito de magia. Ela também neutraliza um item mágico pelo resto da cena. Conjuradores das áreas de efeito podem tentar mantê-la caso sejam bem sucedidos em uma rolagem de Conjuração oposta a Conjuração. Itens mágicos têm +2 de bônus nessa rolagem para cada propriedade mágica contida nele.\n\nConhecimento (Arcano) concede +1 em Conjuração para esta conjuração.",
       "Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Cancelar Magia (Conjuração vs Conjuração)",
                       roll_attr="conjuracao", defense_attr="conjuracao", rng=10, cost_mp=1)]),
    _m("Queimar Magia", "inanis", "Ação", "Uma criatura", "", "Toque", "",
       "Você pronuncia a palavra inanis, enquanto mira um alvo, fazendo com que sua energia arcana queime, deixando seu corpo.\n\nEfeitos: O alvo deve ser bem sucedido em uma rolagem de Agilidade oposta a Conjuração, para não ser tocado por você e perder 2 pontos de magia.\n\nConhecimento (Arcano) concede +1 em Conjuração para esta conjuração.",
       "O alvo perde 4 pontos de magia (apenas Círculo Intermediário) (-). O alvo perde 6 pontos de magia (apenas Círculo Maior) (-). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Queimar Magia (Conjuração vs Agilidade — perde 2 PM)",
                       roll_attr="conjuracao", defense_attr="agilidade", cost_mp=1,
                       damage="2", damage_type="energia", damage_resource="mp",
                       scaling_damage=False)]),
    # --------------------------------- KREO -----------------------------
    _m("Criar", "kreo", "Ação", "Espaço vazio", "", "5m x Círculo x Nível", "Uma hora",
       "Quando pronuncia a palavra kreo, se concentrando no formato do que deseja criar, sua vontade molda a realidade e cria a matéria, dando forma a sua imaginação.\n\nEfeitos: Você cria um objeto do nada, de tamanho médio (uma espada longa, por exemplo). Para conseguir sucesso em criar, você precisa ser bem sucedido em sua rolagem de Conjuração contra um número alvo igual a 10 somado à Dureza mais alta dentre os materiais dos quais o item será composto. Se for bem sucedido, o item surge no espaço escolhido. Os objetos podem ser arremessados em uma criatura como parte da mesma ação usada para criá-los. Caso atinja a criatura, ela deve ser bem sucedida em uma rolagem de Esquiva oposta a Conjuração, para não sofrer dano do tipo apropriado (Concussão +0, Perfuração +0 ou Corte +0).\n\nOfícios concede +1 em Conjuração para esta conjuração.",
       "Cria até 2 objetos (apenas Círculo Intermediário ou Maior) (-4). Cria até 3 objetos (apenas Círculo Maior) (-6). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Criar (Conjuração vs dificuldade 10 + Dureza)",
                       roll_attr="conjuracao", vs_difficulty=True, fixed_difficulty=10,
                       target_mode="none", cost_mp=1)]),
    _m("Reparar", "kreo", "Cena", "Um objeto ou Constructo", "", "Toque", "",
       "Você toca um objeto ou constructo defeituoso enquanto pronuncia a palavra kreo, transmitindo sua energia arcana de forma a repará-lo.\n\nEfeitos: Você recupera 1 ponto da Dureza perdida do objeto com defeito (+1 ponto para cada 2 pontos do seu resultado de Conjuração acima de 10). Quando conjurada em um constructo, ele recupera a mesma quantidade de pontos de vida.\n\nOfícios concede +1 em Conjuração para esta conjuração.",
       "Repara 3 pontos (apenas Círculo Intermediário ou Maior) (-2). Repara 5 pontos (apenas Círculo Maior) (-4). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       img=IMG_HEAL),
    # ------------------------------- KRUCIGON ---------------------------
    _m("Forma Etérea", "krucigon", "Ação", "Uma criatura ou objeto", "", "Toque",
       "Sustentável — Ação Rápida",
       "Tocando uma criatura ou objeto e pronunciando a palavra krucigon, você faz com que ela translade para o Véu Etéreo, ficando intangível.\n\nEfeitos: O alvo fica intangível pela duração da magia.\n\nConhecimento (Religião) concede +1 em Conjuração para esta conjuração.",
       "O alvo não provoca reações de ataque quando se move (apenas Círculo Intermediário ou Maior) (-3). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Forma Etérea (toque)",
                       can_roll=False, cost_mp=1,
                       applies_effects=[applies("Intangível (sustentável)", fx_type="condition",
                                                fx_target="intangivel", duration_mode="scene")])],
       img=IMG_BUFF),
    _m("Teletransporte", "krucigon", "Movimento", "Uma criatura ou objeto", "", "Toque", "",
       "Enquanto sussurra a palavra krucigon, você rasga o véu etéreo, permitindo que você, uma criatura ou um objeto no qual tocar viaje através dos planos.\n\nEfeitos: O alvo é teleportado até uma distância igual a 10m x Círculo x Nível, à sua escolha, em terra firme, para onde você possa ver.\n\nConhecimento (Religião) concede +1 em Conjuração para esta conjuração.",
       "Teleporta o alvo para qualquer lugar do mesmo plano, que você já tenha visitado (apenas Círculo Intermediário ou Maior) (-4). Teleporta o alvo para outro plano, que você já tenha visitado (apenas Círculo Maior) (-6). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Teletransporte (10m x Círculo x Nível)",
                       can_roll=False, target_mode="self", include_self=True, cost_mp=1,
                       movement={"kind": "teleport", "who": "self", "distance": 10,
                                 "ignoreWalls": True})],
       img=IMG_BUFF),
    _m("Invocar", "krucigon", "Ação", "Espaço vazio", "", "Adjacente",
       "Sustentável — Movimento",
       "Você pronuncia a palavra krucigon, trazendo de outro plano uma criatura ou um objeto que você mentalizar.\n\nEfeitos: Você invoca uma criatura pequena com Desafio igual ao dobro do seu nível ou um objeto encantado que lhe dá +1 para um tipo de rolagem relacionada ao objeto. A criatura é amigável a você e a seus aliados e lutará para defendê-los. Você pode usar esta magia para invocar algum pertence que esteja fora do seu alcance, direto para sua mão, que tenha sido vinculado à magia previamente. Você só pode ter um item vinculado por vez.\n\nConhecimento (Religião) concede +1 em Conjuração para esta conjuração.",
       "Invoca criatura média (apenas Círculo Intermediário ou Maior) (-1). Invoca criatura grande (apenas Círculo Maior) (-3). Aumente o Desafio em +1 ponto (apenas Círculo Intermediário ou Maior) (-4). Aumente o Desafio em +3 pontos (apenas Círculo Maior) (-6). O objeto encantado te dá +2 para rolagens relacionadas ao objeto (apenas Círculo Intermediário ou Maior) (-4). O objeto encantado te dá +3 para rolagens relacionadas ao objeto (apenas Círculo Maior) (-6). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1)."),
    # --------------------------------- LUMO -----------------------------
    _m("Luz", "lumo", "Ação", "Um objeto", "", "Toque", "Uma hora",
       "Você pronuncia a palavra lumo enquanto toca um objeto, fazendo com que o mesmo irradie uma luz intensa o suficiente para que todos possam enxergar.\n\nEfeitos: O alvo emite uma luz brilhante que ilumina uma área de 10m multiplicado pelo seu nível, centrada nele.\n\nConhecimento (Arcano) concede +1 em Conjuração para esta conjuração.",
       "O alvo pode ser uma criatura (-2). Revela criaturas escondidas dentro da área no momento da conjuração (apenas Círculo Intermediário ou Maior) (-4). Criaturas invisíveis se tornam visíveis sob a luz desta magia (apenas Círculo Maior) (-6). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1)."),
    _m("Rajada Cromática", "lumo", "Ação", "Um espaço", "", "5m x Círculo x Nível", "Uma cena",
       "Sussurrando a palavra lumo, você lança uma rajada de múltiplas cores em uma direção, causando efeitos diversos àqueles pelos quais a rajada passa.\n\nEfeitos: Você traça uma linha reta entre você e o espaço alvo dentro do alcance. A magia afeta todas as criaturas na linha. Role um dado para cada criatura afetada pela magia. Cada criatura sofrerá uma condição, pela duração da magia, caso não seja bem sucedida em uma rolagem de Percepção oposta a Conjuração, de acordo com o resultado: Pasmo (1 ou 2), Indefeso (3), Atordoado (4), Cego (5), Inconsciente (6). Criaturas cegas não são afetadas por essa magia. Percepção anula esses efeitos.\n\nConhecimento (Arcano) concede +1 em Conjuração para esta conjuração.",
       "A rolagem no dado, para cada criatura, aumenta 1 ponto (apenas Círculo Intermediário ou Maior) (-2). A rolagem no dado, para cada criatura, aumenta 2 pontos (apenas Círculo Maior) (-4). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Rajada Cromática (Conjuração vs Percepção — linha)",
                       roll_attr="conjuracao", target_mode="area", area=1, rng=10,
                       defense_attr="percepcao", cost_mp=1)],
       img=IMG_DMG),
]
