# -*- coding: utf-8 -*-
"""Magias de exemplo (Círculo Menor) — parte 2 (majesto a vitae). Fonte: Sessão 11."""
from builders import magia, effect, cost, action, applies
from data_magias_1 import _m, IMG, IMG_DMG, IMG_BUFF, IMG_HEAL

MAGIAS_2 = [
    # ------------------------------- MAJESTO ----------------------------
    _m("Aumentar", "majesto", "Ação", "Uma criatura ou objeto", "", "Toque", "Uma cena",
       "Pronunciando a palavra majesto enquanto toca seu alvo com a palma de sua mão, faz com que suas proporções aumentem de forma descomunal.\n\nEfeitos: Aumenta em uma categoria o tamanho do alvo. Adicionalmente, criaturas afetadas por essa magia recebem 1D em Força e Vigor pela duração da magia.\n\nConhecimento (Arcano) concede +1 em Conjuração para esta conjuração.",
       "Aumenta em 2 categorias, 1D em Força, 2D em Vigor (apenas Círculo Intermediário ou Maior) (-3). Aumenta em 3 categorias, 2D em Força e Vigor (apenas Círculo Maior) (-5). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Aumentar (toque — 1D Força e Vigor)",
                       can_roll=False, cost_mp=1,
                       applies_effects=[
                           applies("Aumentado: 1D Força", fx_type="dice", fx_target="forca",
                                   fx_value=1, duration_mode="scene"),
                           applies("Aumentado: 1D Vigor", fx_type="dice", fx_target="vigor",
                                   fx_value=1, duration_mode="scene"),
                       ])],
       img=IMG_BUFF),
    _m("Diminuir", "majesto", "Ação", "Uma criatura ou objeto", "", "Toque", "Uma cena",
       "Você toca o alvo com um dos dedos enquanto sussurra a palavra majesto, encolhendo seu alvo a um tamanho incomum.\n\nEfeitos: Diminui em uma categoria o tamanho do alvo. Adicionalmente, criaturas afetadas por essa magia recebem 1D em Agilidade e rolagens para se esconder pela duração da magia.\n\nConhecimento (Arcano) concede +1 em Conjuração para esta conjuração.",
       "Diminui em 2 categorias, 1D em Agilidade e 2D em rolagens para esconder-se (apenas Círculo Intermediário ou Maior) (-2). Diminui em 3 categorias, 2D em Agilidade e rolagens para se esconder (apenas Círculo Maior) (-4). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Diminuir (toque — 1D Agilidade)",
                       can_roll=False, cost_mp=1,
                       applies_effects=[applies("Diminuído: 1D Agilidade", fx_type="dice",
                                                fx_target="agilidade", fx_value=1,
                                                duration_mode="scene")])],
       img=IMG_BUFF),
    # -------------------------------- MENSO -----------------------------
    _m("Telecinésia", "menso", "Ação", "Uma criatura ou objeto", "", "3m x Círculo x Nível",
       "Uma cena",
       "Você pronuncia a palavra menso, enquanto foca sua visão em um objeto ou criatura, podendo arrastá-lo segundo sua vontade.\n\nEfeitos: Quando você conjura esta magia, o alvo deve ser bem sucedido em uma rolagem de Força oposta a Conjuração, para não ficar imobilizado (Força anula). Enquanto o alvo estiver imobilizado, você pode movê-lo com a força da sua mente até 5m usando sua ação, mas não pode deixar o alcance da magia. Você pode mover objetos médios (uma espada longa, por exemplo) ou menores, podendo atacar com eles como parte dessa ação usando o atributo de Mente, em vez do atributo padrão da arma. Se o alvo for uma criatura, ele pode sofrer reações de ataque quando você o movimenta. Sempre que você mover o alvo desta forma, ele termina o movimento derrubado.\n\nVontade de Ferro concede +1 em Conjuração para esta conjuração.",
       "Você pode mover o alvo 10m (apenas Círculo Intermediário ou Maior) (-2). Você pode mover o alvo 15m (apenas Círculo Maior) (-4). Você pode mover o alvo através de espaços ocupados; criaturas no trajeto precisam esquivar da magia ou serão derrubadas (apenas Círculo Intermediário ou Maior) (-4). Necessita de componentes gestuais (apenas Círculo Menor) (+1).",
       actions=[action("Telecinésia (Conjuração vs Força)",
                       roll_attr="conjuracao", defense_attr="forca", rng=6, cost_mp=1,
                       applies_effects=[applies("Imobilizado — telecinese (Força anula)",
                                                fx_type="condition", fx_target="telecinese",
                                                duration_mode="scene", resist=True,
                                                resist_attr="forca")])]),
    _m("Telepatia", "menso", "Ação Rápida", "Uma criatura", "", "5m x Círculo x Nível", "",
       "Após sussurrar a palavra menso, você foca-se nas suas lembranças de um indivíduo que você conheça e envia mentalmente uma mensagem a ele.\n\nEfeitos: Você pode enviar uma mensagem mentalmente para o alvo. Se o alvo for bem sucedido em uma rolagem de Mente (Normal), ele pode ser capaz de responder de volta mentalmente. Você precisa ter tido algum diálogo com o alvo alguma vez para que esta magia funcione.\n\nVontade de Ferro concede +1 em Conjuração para esta conjuração. Carisma concede +1 em Conjuração para esta conjuração.",
       "Alcance (5km x Círculo x Nível) (apenas Círculo Intermediário ou Maior) (-3). Alcance (Qualquer lugar) (apenas Círculo Maior) (-5). O alvo não pode responder de volta (+2). Você não precisa ter tido diálogo com o alvo antes (apenas Círculo Intermediário ou Maior) (-2). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1)."),
    _m("Empurrão Cinético", "menso", "Ação", "", "5m", "Emanação", "",
       "Você pronuncia a palavra menso, fazendo com que uma força invisível maciça ao seu redor empurre todos ao seu redor para longe de você.\n\nDano: Concussão +1 (Esquiva ou Bloqueio).\n\nEfeitos: Criaturas dentro da área são empurradas uma quantidade de metros igual ao dano sofrido.\n\nVontade de Ferro concede +1 em Conjuração para esta conjuração.",
       "Dano: Concussão +2 (apenas Círculo Intermediário) (-). Dano: Concussão +3 (apenas Círculo Maior) (-). Alvos de tamanho Médio ou menor são também derrubados (-4). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Empurrão Cinético (Conjuração vs Esquiva/Bloqueio — empurra)",
                       roll_attr="conjuracao", target_mode="aura", area=5,
                       damage="1", damage_type="concussao",
                       defense_attr="esquiva", defense_attr2="bloqueio", cost_mp=1,
                       movement={"kind": "push", "who": "targets", "distance": 2})],
       img=IMG_DMG),
    # -------------------------------- MORTIS ----------------------------
    _m("Raio Necrótico", "mortis", "Ação", "Uma criatura", "", "5m x Círculo x Nível", "",
       "Você pronuncia a palavra mortis, concentrando energias necromânticas na palma de suas mãos e lançando-a contra seu inimigo.\n\nDano: Necrótico +1 (Esquiva).\n\nEfeitos: Se o alvo sofrer dano, ele deve ser bem sucedido em uma rolagem de Vigor oposta a Conjuração, ou sofrerá dano contínuo necrótico até o fim da cena (Vigor anula).\n\nConhecimento (Ocultismo) concede +1 em Conjuração para esta conjuração. Medicina concede +1 em Conjuração para esta conjuração.",
       "Dano: Necrótico +2 (apenas Círculo Intermediário) (-). Dano: Necrótico +3 (apenas Círculo Maior) (-). Se o alvo sofrer dano, ele deve ser bem sucedido em uma rolagem de Vigor oposta a Conjuração, ou ficará enfraquecido até o fim da cena (Vigor anula) (-2). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Raio Necrótico (Conjuração vs Esquiva)",
                       roll_attr="conjuracao", damage="1", damage_type="necrotico",
                       defense_attr="esquiva", rng=10, cost_mp=1,
                       applies_effects=[applies("Dano contínuo necrótico (Vigor anula)",
                                                fx_type="condition", fx_target="dano_continuo",
                                                duration_mode="scene", resist=True,
                                                resist_attr="vigor", tick_amount=1,
                                                tick_type="necrotico")])],
       img=IMG_DMG),
    _m("Invocar os Mortos", "mortis", "Ação",
       "Uma criatura de Desafio igual a duas vezes o seu nível ou menos", "", "Toque",
       "Permanente",
       "Tocando uma criatura sem vida e pronunciando a palavra mortis, você preenche o corpo vazio com energias necromânticas, trazendo-a de volta em um estado de não vida.\n\nEfeitos: O alvo retorna à vida com metade dos pontos de vida e recebe o modelo Zumbi, com pontuação igual ao seu nível -1. Você necessita do corpo inteiro da criatura.\n\nConhecimento (Ocultismo) concede +1 em Conjuração para esta conjuração. Medicina concede +1 em Conjuração para esta conjuração.",
       "Uma criatura de Desafio igual a três vezes o seu nível ou menos (apenas Círculo Intermediário ou Maior) (-6). Uma criatura de Desafio igual a quatro vezes o seu nível ou menos (apenas Círculo Maior) (-8). Traz o alvo de volta à vida com todos os pontos de vida (-4). Necessita apenas de parte do corpo dele (apenas Círculo Intermediário ou Maior) (-4). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1)."),
    _m("Toque Vampírico", "mortis", "Ação", "Uma criatura", "", "Toque", "",
       "Você pronuncia a palavra mortis enquanto toca seu alvo. Energias necromânticas percorrem seus corpos, transferindo a energia de seu alvo para você.\n\nDano: Necrótico +1 (Esquiva).\n\nEfeitos: Caso esse ataque cause dano escalonado, você recupera pontos de vida igual ao dano escalonado causado. Se o alvo sofrer dano desse ataque, ele deve ser bem sucedido em uma rolagem de Vigor oposta a Conjuração, ou ficará enfraquecido até o fim da cena (Vigor anula).\n\nConhecimento (Ocultismo) concede +1 em Conjuração para esta conjuração. Medicina concede +1 em Conjuração para esta conjuração.",
       "Se o alvo sofrer dano, ele deve ser bem sucedido em uma rolagem de Vigor oposta a Conjuração, ou ficará exausto até o fim da cena (Vigor anula) (apenas Círculo Intermediário ou Maior) (-4). O dano escalonado recupera seus pontos de magia, em vez dos pontos de vida (-1). Você recupera pontos de magia igual aos pontos de vida recuperados (apenas Círculo Intermediário ou Maior) (-4). Um aliado até 5m recupera os pontos de magia, em vez de você (-2). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Toque Vampírico (Conjuração vs Esquiva — drena vida)",
                       roll_attr="conjuracao", damage="1", damage_type="necrotico",
                       defense_attr="esquiva", cost_mp=1,
                       applies_effects=[applies("Enfraquecido (Vigor anula)",
                                                fx_type="condition", fx_target="enfraquecido",
                                                duration_mode="scene", resist=True,
                                                resist_attr="vigor")])],
       img=IMG_DMG),
    # -------------------------------- NOXIA -----------------------------
    _m("Nuvem Tóxica", "noxia", "Ação", "", "1m x Nível", "3m x Círculo x Nível", "",
       "Sussurrando a palavra noxia, você conjura uma nuvem tóxica que afeta os sentidos das criaturas dentro dela, deixando-as debilitadas pouco a pouco.\n\nEfeitos: Criaturas dentro da área, que falharem em uma rolagem de Vigor oposta a Conjuração, sofrerão dano contínuo de veneno até o fim da cena (Cuidados Médicos anula).\n\nOfícios concede +1 em Conjuração para esta conjuração.",
       "O alvo também fica imobilizado até o fim da cena (apenas Círculo Maior) (Vigor anula) (-2). O alvo também fica cego até o fim da cena (apenas Círculo Maior) (Vigor anula) (-2). O alvo também fica atordoado até o fim da cena (apenas Círculo Maior) (Vigor anula) (-4). O alvo também fica enfraquecido até o fim da cena (apenas Círculo Intermediário ou Maior) (Vigor anula) (-2). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Nuvem Tóxica (Conjuração vs Vigor — área)",
                       roll_attr="conjuracao", target_mode="area", area=2, rng=6,
                       defense_attr="vigor", cost_mp=1,
                       applies_effects=[applies("Dano contínuo de veneno (Cuidados Médicos anula)",
                                                fx_type="condition", fx_target="dano_continuo",
                                                duration_mode="scene", resist=True,
                                                resist_attr="vigor", tick_amount=1,
                                                tick_type="veneno")])],
       img=IMG_DMG),
    _m("Toque Venenoso", "noxia", "Ação", "Uma criatura", "", "Toque", "",
       "Você pronuncia a palavra noxia enquanto toca uma criatura viva. Seu toque libera um forte veneno que penetra através da pele da criatura, afetando seu organismo.\n\nDano: Veneno +1 (Esquivável).\n\nEfeitos: Se o alvo sofrer dano, ele deve ser bem sucedido em uma rolagem de Vigor oposta a Conjuração, ou sofrerá dano contínuo de veneno até o fim da cena (Cuidados Médicos anula).\n\nOfícios concede +1 em Conjuração para esta conjuração.",
       "Dano: Veneno +2 (apenas Círculo Intermediário) (-). Dano: Veneno +3 (apenas Círculo Maior) (-). Não afeta um determinado tipo de criatura (+1). Afeta apenas um tipo de criatura (+2). O alvo fica enfraquecido enquanto estiver sofrendo dano contínuo (apenas Círculo Intermediário) (-4). O alvo fica cego enquanto estiver sofrendo dano contínuo (apenas Círculo Maior) (-4). O alvo fica paralisado enquanto estiver sofrendo dano contínuo (apenas Círculo Maior) (-4). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Toque Venenoso (Conjuração vs Esquiva — toque)",
                       roll_attr="conjuracao", damage="1", damage_type="veneno",
                       defense_attr="esquiva", cost_mp=1,
                       applies_effects=[applies("Dano contínuo de veneno (Cuidados Médicos anula)",
                                                fx_type="condition", fx_target="dano_continuo",
                                                duration_mode="scene", resist=True,
                                                resist_attr="vigor", tick_amount=1,
                                                tick_type="veneno")])],
       img=IMG_DMG),
    # ------------------------------- PLURIBUS ---------------------------
    _m("Replicar", "pluribus", "Reação", "Uma criatura", "", "3m x Círculo x Nível", "",
       "Quando você nota uma ação que favoreça você e seu grupo, você sussurra rapidamente a palavra pluribus, distorcendo o espaço-tempo e fazendo com que a ação se repita.\n\nEfeitos: Quando uma criatura dentro do alcance faz uma ação, você pode conjurar esta magia sobre ela, fazendo com que ela repita a ação que engatilhou esta magia. Caso a ação tenha algum custo, como pontos de magia, vida ou heróicos, você deve pagar por ela.\n\nConhecimento (Arcano) concede +1 em Conjuração para esta conjuração.",
       "A criatura recebe +1 para rolagens da ação repetida (-2). A criatura recebe +2 para rolagens da ação repetida (-4). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1)."),
    _m("Simular", "pluribus", "Reação", "Conjurador", "", "5m x Círculo", "",
       "Você analisa uma ação e, pronunciando a palavra pluribus, você consegue replicá-la de forma perfeita.\n\nEfeitos: Quando uma criatura dentro do alcance executa uma ação, você usa sua reação para repetir tudo o que ela fez. Você pode copiar a magia conjurada por alguém usando o atributo de Conjuração dela, mesmo que não conheça as palavras arcanas; você pode copiar um ataque com arma de alguém usando o bônus de ataque dele, mesmo que não possua uma arma igual, e causará o mesmo dano base. Quando copia qualquer ação que requeira gasto de pontos de vida, pontos de magia ou pontos heróicos, você deve pagar o mesmo para copiar.\n\nConhecimento (Arcano) concede +1 em Conjuração para esta conjuração.",
       "Se sua rolagem nessa reação for uma falha crítica, você fica atordoado até o fim da cena (Mente anula) (+2). Você recebe +1 para a rolagem da ação copiada (-2). Você recebe +2 para a rolagem da ação copiada (-4). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1)."),
    # ------------------------------ SAECULORUM --------------------------
    _m("Lentidão", "saeculorum", "Ação", "Uma criatura", "", "3m x Círculo x Nível", "Uma cena",
       "Você sussurra a palavra saeculorum, distorcendo o tempo em volta de seu alvo, fazendo com que tudo se mova rápido demais para ele.\n\nEfeitos: O alvo deve ser bem sucedido em uma rolagem de Agilidade oposta a Conjuração ou ficará lento e não poderá fazer reações pela duração da magia (Agilidade anula).\n\nConhecimento (Arcano) concede +1 em Conjuração para esta conjuração.",
       "O alvo fica imobilizado e não pode fazer reações até o fim da cena (Agilidade anula) (apenas Círculo Intermediário ou Maior) (-2). O alvo fica paralisado até o fim da cena (Agilidade anula) (apenas Círculo Maior) (-4). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Lentidão (Conjuração vs Agilidade)",
                       roll_attr="conjuracao", defense_attr="agilidade", rng=6, cost_mp=1,
                       applies_effects=[applies("Lento, sem reações (Agilidade anula)",
                                                fx_type="condition", fx_target="lento",
                                                duration_mode="scene", resist=True,
                                                resist_attr="agilidade")])]),
    _m("Velocidade", "saeculorum", "Ação", "Uma criatura", "", "Toque", "Uma cena",
       "Você toca seu alvo enquanto pronuncia a palavra saeculorum, fazendo com que o tempo flua mais devagar para ele.\n\nEfeitos: O alvo recebe uma ação de movimento adicional em cada um de seus turnos, pela duração da magia.\n\nConhecimento (Arcano) concede +1 em Conjuração para esta conjuração.",
       "O alvo recebe uma reação adicional (em vez de movimento) (-2). O alvo recebe uma ação adicional (em vez de movimento) (apenas Círculo Intermediário ou Maior) (-6). O alvo recebe um turno adicional (em vez de movimento) (apenas Círculo Maior) (-8). O alvo recebe dois turnos adicionais (em vez de movimento) (apenas Círculo Maior) (-10). O alvo sofre 1 ponto de dano por rodada enquanto estiver sob efeito da magia (+2). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       img=IMG_BUFF),
    _m("Viagem Temporal", "saeculorum", "Cena", "Conjurador", "", "", "Uma rodada",
       "Você pronuncia saeculorum, para ser tragado pelo tempo, sendo lançado de volta ou adiante, dependendo da sua vontade enquanto pronuncia.\n\nEfeitos: Você pode viajar uma cena para o passado, alterando o mesmo pela duração da magia. Você também pode viajar uma cena para o futuro, obtendo informações, pela duração da magia.\n\nConhecimento (História) concede +1 em Conjuração para esta conjuração. Você precisa gastar 1 ponto heróico para conjurar essa magia.",
       "Viajar uma hora pro passado ou pro futuro, em vez de uma cena (apenas Círculo Intermediário ou Maior) (-2). Duração (Uma cena) (apenas Círculo Intermediário ou Maior) (-4). Viajar um dia pro passado ou pro futuro, em vez de uma cena (apenas Círculo Maior) (-6). Duração (Uma hora) (apenas Círculo Maior) (-8). Você perde 1 ponto de vida quando conjura esta magia (+1). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       costs=[cost("mp", 1, "Círculo Menor"), cost("heroic", 1, "Custo da magia")]),
    # -------------------------------- SANGON ----------------------------
    _m("Transmutar Matéria", "sangon", "Ação", "Um objeto", "", "Toque", "Cena",
       "Você toca um objeto enquanto pronuncia a palavra sangon, alterando suas propriedades químicas.\n\nEfeitos: Você toca um objeto e altera o Material do qual ele é feito, realizando uma rolagem de Conjuração contra uma dificuldade de número 10 + Dureza do Material do objeto. Se for bem sucedido, o Material do objeto muda para um Material com a Dureza anterior +1/-1 para cada 2 pontos do resultado acima do número alvo.\n\nConhecimento (Natureza) concede +1 em Conjuração para esta conjuração.",
       "Dureza anterior +2/-2 (apenas Círculo Intermediário ou Maior) (-4). Dureza anterior +3/-3 (apenas Círculo Maior) (-6). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Transmutar Matéria (Conjuração vs 10 + Dureza)",
                       roll_attr="conjuracao", vs_difficulty=True, fixed_difficulty=10,
                       target_mode="none", cost_mp=1)]),
    _m("Transmutar Criatura", "sangon", "Ação", "Uma criatura", "", "Toque", "Cena",
       "Você pronuncia a palavra sangon enquanto toca uma criatura com a palma de sua mão, alterando sua estrutura física ou parte dela.\n\nEfeitos: Há duas formas de se transmutar uma criatura: a transmutação parcial e a completa. O alvo pode resistir à magia com uma rolagem bem sucedida de Vigor oposta a Conjuração, ou ficará transmutado pela duração da magia (Vigor anula). Na transmutação parcial, você altera apenas uma parte do corpo do alvo, transformando em parte de uma outra criatura. O alvo troca um de seus traços por um traço de uma criatura cujos Pontos de Criação custem no máximo a metade do seu nível (ou o mesmo valor em um custo negativo, caso o alvo seja um inimigo). Um mesmo alvo pode sofrer mais de uma transmutação parcial. Na transmutação completa, você altera totalmente a forma física do alvo para a forma física de uma criatura de Desafio 2 x Nível, mantendo apenas seus pontos de vida, pontos de magia, pontos heróicos e Mente originais. A criatura recebe um bônus para a rolagem igual à diferença entre seu Desafio atual e o Desafio da criatura na qual ela será transformada.\n\nConhecimento (Natureza) concede +1 em Conjuração para esta conjuração.",
       "O Desafio da Transmutação Completa aumenta em +2 (apenas Círculo Intermediário ou Maior) (-6). O Desafio da Transmutação Completa aumenta em +4 (apenas Círculo Maior) (-8). Apenas Parcial, aumentar +2 nos Pontos de Criação (-3). O alvo recebe o traço da outra criatura sem ter que perder um seu em troca (-2). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Transmutar Criatura (Conjuração vs Vigor)",
                       roll_attr="conjuracao", defense_attr="vigor", cost_mp=1)]),
    # -------------------------------- SANKTA ----------------------------
    _m("Chama Sagrada", "sankta", "Ação", "Uma criatura", "", "5m x Círculo x Nível", "",
       "Pronunciando a palavra sankta, você faz com que uma chama desça sobre o alvo queimando sua carne e sua alma.\n\nDano: Radiante +1 (Esquiva).\n\nEfeitos: Criaturas com Corrupção 8 ou maior, que sofrerem dano, devem ser bem sucedidas em uma rolagem de Mente ou perderão 1 ponto de Corrupção (não funciona com criaturas com a mesma corrupção que você ou menor).\n\nConhecimento (Religião) concede +1 em Conjuração para esta conjuração.",
       "Dano: Radiante +2 (apenas Círculo Intermediário) (-). Dano: Radiante +3 (apenas Círculo Maior) (-). O alvo perde 2 pontos de Corrupção (em vez de 1) (apenas Círculo Intermediário) (-4). O alvo perde 3 pontos de Corrupção (em vez de 1) (apenas Círculo Maior) (-6). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Chama Sagrada (Conjuração vs Esquiva)",
                       roll_attr="conjuracao", damage="1", damage_type="radiante",
                       defense_attr="esquiva", rng=10, cost_mp=1)],
       img=IMG_DMG),
    _m("Consagrar", "sankta", "Ação", "", "1m x Nível", "Emanação", "",
       "Sussurrando a palavra sankta, enquanto toca seu peito, você faz com que a área ao seu redor emane energia sagrada, afetando a você e seus aliados de forma positiva e ferindo seus inimigos.\n\nDano: Radiante +0 (Esquiva).\n\nEfeitos: Você e todos os seus aliados dentro da área cancelam condições de Controlado, Enfeitiçado e Abalado. Criaturas dentro da área, com Corrupção 6 ou mais, devem ser bem sucedidas em uma rolagem de Mente oposta a Conjuração para não perderem 1 ponto de Corrupção (não funciona com criaturas com a mesma corrupção que você ou menor).\n\nConhecimento (Religião) concede +1 em Conjuração para esta conjuração.",
       "Dano: Radiante +1 (apenas Círculo Intermediário) (-). Dano: Radiante +2 (apenas Círculo Maior) (-). Criaturas afetadas ficam pasmas até o fim da cena (Mente anula) (apenas Círculo Intermediário ou Maior) (-2). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Consagrar (Conjuração vs Esquiva — emanação)",
                       roll_attr="conjuracao", target_mode="aura", area=2,
                       damage="0", damage_type="radiante", defense_attr="esquiva", cost_mp=1)],
       img=IMG_HEAL),
    # -------------------------------- SONIGU ----------------------------
    _m("Ensurdecer", "sonigu", "Ação", "", "1m x Nível", "3m x Círculo x Nível", "",
       "Pronunciando a palavra sonigu, você manipula as frequências sonoras em uma área, de forma a ensurdecer as criaturas presentes nela.\n\nEfeitos: Todas as criaturas dentro da área devem ser bem sucedidas em uma rolagem de Vigor oposta a Conjuração, ou ficarão surdas (Percepção anula).\n\nConhecimento (Natureza) concede +1 em Conjuração para esta conjuração.",
       "O alvo também fica pasmo até o fim da cena (apenas Círculo Intermediário ou Maior) (Vigor anula) (-2). O alvo também fica atordoado até o fim da cena (apenas Círculo Maior) (Vigor anula) (-4). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Ensurdecer (Conjuração vs Vigor — área)",
                       roll_attr="conjuracao", target_mode="area", area=2, rng=6,
                       defense_attr="vigor", cost_mp=1,
                       applies_effects=[applies("Surdo (Percepção anula)", fx_type="condition",
                                                fx_target="surdo", duration_mode="scene",
                                                resist=True, resist_attr="percepcao")])]),
    _m("Imitar Sons", "sonigu", "Ação", "Um espaço vazio", "", "3m x Círculo x Nível", "Uma cena",
       "Você sussurra a palavra sonigu, manipulando o vento de forma a criar sons e vozes.\n\nEfeitos: Cria um som que o conjurador já conheça. Todos os que puderem ouvir o som devem ser bem sucedidos em uma rolagem de Percepção oposta a Conjuração, para notar que se trata de um som falso.\n\nCarisma concede +1 em Conjuração para esta conjuração. Conhecimento (Natureza) concede +1 em Conjuração para esta conjuração.",
       "Se usado para imitar a voz de alguém, você recebe 1D em rolagens para interagir socialmente para quem ouve o som (apenas Círculo Intermediário ou Maior) (-2). Se usado para imitar a voz de alguém, resultados 1 nos dados são considerados 3 para interagir socialmente com quem ouve a voz (apenas Círculo Maior) (-4). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1)."),
    _m("Rajada Sônica", "sonigu", "Ação", "Uma criatura ou objeto", "", "5m x Círculo x Nível", "",
       "Você pronuncia a palavra sonigu e sua magia cria poderosas ondas sonoras através do deslocamento de ar em torno do seu alvo, ferindo-o e deixando-o surdo, caso seja uma criatura.\n\nDano: Sônico +1 (Esquiva ou Bloqueio).\n\nEfeitos: Se o alvo sofrer dano, ele deve ser bem sucedido em uma rolagem de Vigor oposta a Conjuração, ou ficará surdo até o fim da cena (Vigor anula).\n\nConhecimento (Natureza) concede +1 em Conjuração para esta conjuração.",
       "Dano: Sônico +2 (apenas Círculo Intermediário) (-). Dano: Sônico +3 (apenas Círculo Maior) (-). O alvo fica sob efeito de dano sônico contínuo até o fim da cena (Vigor anula) (apenas Círculo Maior) (-2). O alvo fica pasmo até o fim da cena (Vigor anula) (apenas Círculo Intermediário ou Maior) (-2). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Rajada Sônica (Conjuração vs Esquiva/Bloqueio)",
                       roll_attr="conjuracao", damage="1", damage_type="sonico",
                       defense_attr="esquiva", defense_attr2="bloqueio", rng=10, cost_mp=1,
                       applies_effects=[applies("Surdo (Vigor anula)", fx_type="condition",
                                                fx_target="surdo", duration_mode="scene",
                                                resist=True, resist_attr="vigor")])],
       img=IMG_DMG),
    _m("Silêncio", "sonigu", "Ação", "", "1m x Nível", "3m x Círculo x Nível",
       "Sustentável — Ação Rápida",
       "Você sussurra a palavra sonigu, anulando todas as ondas sonoras em uma determinada área.\n\nEfeitos: Nenhum som pode ser emitido dentro da área. Criaturas que tentem emitir qualquer som dentro da área da magia devem ser bem sucedidas em uma rolagem de Força oposta a Conjuração. Magias que sejam compostas pela palavra sonigu não têm efeito nesta área, além desta já conjurada, a menos que o conjurador da outra magia seja bem sucedido em uma rolagem de Conjuração oposta a Conjuração.\n\nConhecimento (Natureza) concede +1 em Conjuração para esta conjuração.",
       "Magias compostas pela palavra sonigu têm efeito na área (-2). Magias compostas pela palavra sonigu têm efeito na área, mas somente as que você conjurar (apenas Círculo Intermediário ou Maior) (-6). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1)."),
    # ------------------------------ SORCDIRON ---------------------------
    _m("Aumento Arcano", "sorcdiron", "Ação Rápida", "Uma criatura", "", "Toque", "Uma cena",
       "Você toca seu alvo e pronuncia a palavra sorcdiron, aprimorando temporariamente alguma de suas qualidades.\n\nEfeitos: Você pode dar ao alvo um dos seguintes benefícios: 1 ponto de sobrevida para cada 2 pontos da sua rolagem de Conjuração acima de 10; bônus de +1 em ataques corpo a corpo; bônus de +1 em ataques à distância; bônus de +1 em Deslocamento; bônus de +1 na Iniciativa; bônus de +1 na Esquiva; bônus de +1 no Bloqueio; bônus de +1 em Conjuração.\n\nConhecimento (Religião) concede +1 em Conjuração para esta conjuração.",
       "O alvo recebe dois efeitos à escolha do conjurador, em vez de um (apenas Círculo Intermediário ou Maior) (-4). O alvo recebe três efeitos à escolha do conjurador, em vez de um (apenas Círculo Maior) (-8). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[
           action("Aumento Arcano: +1 Esquiva (cena)", can_roll=False, cost_mp=1,
                  applies_effects=[applies("Aumento Arcano: +1 Esquiva", fx_type="bonus",
                                           fx_target="esquiva", fx_value=1,
                                           duration_mode="scene")]),
           action("Aumento Arcano: +1 Bloqueio (cena)", can_roll=False, cost_mp=1,
                  applies_effects=[applies("Aumento Arcano: +1 Bloqueio", fx_type="bonus",
                                           fx_target="bloqueio", fx_value=1,
                                           duration_mode="scene")]),
           action("Aumento Arcano: +1 ataques (cena)", can_roll=False, cost_mp=1,
                  applies_effects=[applies("Aumento Arcano: +1 ataques", fx_type="bonus",
                                           fx_target="attack", fx_value=1,
                                           duration_mode="scene")]),
           action("Aumento Arcano: +1 Conjuração (cena)", can_roll=False, cost_mp=1,
                  applies_effects=[applies("Aumento Arcano: +1 Conjuração", fx_type="bonus",
                                           fx_target="conjuracao", fx_value=1,
                                           duration_mode="scene")]),
       ],
       img=IMG_BUFF),
    _m("Encantar Objeto", "sorcdiron", "Ação Rápida", "Um objeto não mágico", "", "Toque",
       "Uma cena",
       "Sussurrando a palavra sorcdiron, enquanto toca um objeto, você aprimora sua eficiência, como se o tornasse mágico.\n\nEfeitos: Todas as rolagens utilizando o objeto encantado recebem +1, desde que utilizado para a função para a qual fora feito.\n\nConhecimento (Religião) concede +1 em Conjuração para esta conjuração.",
       "As rolagens utilizando o objeto recebem +2, em vez de +1 (apenas Círculo Intermediário ou Maior) (-). As rolagens utilizando o objeto recebem +3, em vez de +1 (apenas Círculo Maior) (-). Só funciona em objetos compostos por um material específico (+2). Não funciona em objetos compostos por material específico (+1). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       img=IMG_BUFF),
    _m("Melhoria Arcana", "sorcdiron", "Ação Rápida", "Uma criatura", "", "Toque", "Uma cena",
       "Enquanto profere a palavra sorcdiron e toca seu alvo, o mesmo sente uma energia percorrer seu corpo, aprimorando suas capacidades.\n\nEfeitos: O alvo recebe 1D em um atributo à escolha do conjurador.\n\nConhecimento (Religião) concede +1 em Conjuração para esta conjuração.",
       "Sempre que o alvo rolar 1 em um dado, numa rolagem desse atributo, ele pode re-rolar o dado (apenas Círculo Intermediário ou Maior) (-4). Sempre que o alvo rolar 1 ou 2 em um dado, numa rolagem desse atributo, ele pode re-rolar o dado (apenas Círculo Intermediário ou Maior) (-8). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Melhoria Arcana (1D em um atributo — escolha ao aplicar)",
                       can_roll=False, cost_mp=1,
                       applies_effects=[applies("Melhoria Arcana: 1D no atributo (edite o alvo)",
                                                fx_type="dice", fx_target="forca", fx_value=1,
                                                duration_mode="scene")])],
       img=IMG_BUFF),
    # ------------------------------- TENEBRAE ---------------------------
    _m("Cegueira", "tenebrae", "Ação", "Uma criatura", "", "5m x Círculo x Nível", "Uma cena",
       "Você pronuncia tenebrae, enquanto foca sua visão em um único alvo. Os olhos do alvo vibram até arder e se tornam incapazes de absorver a luz.\n\nEfeitos: O alvo deve ser bem sucedido em uma rolagem de Percepção oposta a Conjuração, ou fica cego pela duração da magia (Percepção anula).\n\nConhecimento (Ocultismo) concede +1 em Conjuração para esta conjuração.",
       "É necessário ser bem sucedido em uma rolagem de Mente para anular também (apenas Círculo Intermediário ou Maior) (-2). É necessário ser bem sucedido em uma rolagem de Mente e de Vigor para anular também (apenas Círculo Maior) (-4). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Cegueira (Conjuração vs Percepção)",
                       roll_attr="conjuracao", defense_attr="percepcao", rng=10, cost_mp=1,
                       applies_effects=[applies("Cego (Percepção anula)", fx_type="condition",
                                                fx_target="cego", duration_mode="scene",
                                                resist=True, resist_attr="percepcao")])]),
    _m("Escuridão", "tenebrae", "Ação", "", "1m x Nível", "3m x Círculo x Nível",
       "Sustentável — Ação Rápida",
       "Você pronuncia a palavra tenebrae, lançando uma escuridão profunda e sinistra sobre uma área, deixando cegas todas as criaturas dentro dela.\n\nEfeitos: Você conjura uma escuridão densa por toda a área da magia. Nenhuma fonte de iluminação não mágica funciona dentro da área. Todas as criaturas que iniciarem seus turnos ou entrarem dentro da área ficam cegas enquanto estiverem dentro dela (o conjurador não é afetado). Conjurar fontes de luz dentro dessa área requer ser bem sucedido em uma rolagem de Conjuração oposta a Conjuração.\n\nConhecimento (Ocultismo) concede +1 em Conjuração para esta conjuração.",
       "A área da magia se torna também terreno difícil (apenas Círculo Intermediário ou Maior) (-4). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Escuridão (área persistente — cega quem entra)",
                       can_roll=False, target_mode="area", area=2, rng=6, cost_mp=1,
                       persist_area=True, persist_rounds=0, persist_trigger="both",
                       applies_effects=[applies("Cego (dentro da área)", fx_type="condition",
                                                fx_target="cego", duration_mode="rounds",
                                                duration_rounds=1)])]),
    # ------------------------------- TRAUMATO ---------------------------
    _m("Rajada Psíquica", "traumato", "Ação", "Uma criatura ou objeto", "",
       "5m x Círculo x Nível", "",
       "Pronunciando a palavra traumato, você lança a uma criatura, ao alcance da sua visão, uma rajada que destrói a sua mente.\n\nDano: Psíquico +1 (Mente).\n\nEfeitos: Se o alvo sofrer dano, ele deve ser bem sucedido em uma rolagem de Mente oposta a Conjuração, ou ficará pasmo até o fim da cena (Mente anula).\n\nCarisma concede +1 em Conjuração para esta conjuração.",
       "Dano: Psíquico +2 (apenas Círculo Intermediário) (-). Dano: Psíquico +3 (apenas Círculo Maior) (-). O alvo fica abalado até o fim da cena (Mente anula) (apenas Círculo Intermediário ou Maior) (-2). O alvo fica atordoado até o fim da cena (Mente anula) (apenas Círculo Maior) (-4). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Rajada Psíquica (Conjuração vs Mente)",
                       roll_attr="conjuracao", damage="1", damage_type="psiquico",
                       defense_attr="mente", rng=10, cost_mp=1,
                       applies_effects=[applies("Pasmo (Mente anula)", fx_type="condition",
                                                fx_target="pasmo", duration_mode="scene",
                                                resist=True, resist_attr="mente")])],
       img=IMG_DMG),
    _m("Tempestade Mental", "traumato", "Ação", "", "1m x Nível", "3m x Círculo x Nível", "",
       "Você sussurra a palavra traumato, invocando uma tempestade dentro das mentes das criaturas dentro de uma área.\n\nDano: Psíquico +1 (Mente).\n\nEfeitos: Se uma criatura sofrer dano, ela deve ser bem sucedida em uma rolagem de Mente ou ficará atordoada até o fim da cena (Mente anula).\n\nCarisma concede +1 em Conjuração para esta conjuração.",
       "O alvo cai no chão (-1). O alvo sofre dano contínuo psíquico até o fim da cena (Mente anula) (apenas Círculo Maior) (-4). O alvo fica abalado até o fim da cena (Mente anula) (apenas Círculo Maior) (-4). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Tempestade Mental (Conjuração vs Mente — área)",
                       roll_attr="conjuracao", target_mode="area", area=2, rng=6,
                       damage="1", damage_type="psiquico", defense_attr="mente", cost_mp=1,
                       applies_effects=[applies("Atordoado (Mente anula)", fx_type="condition",
                                                fx_target="atordoado", duration_mode="scene",
                                                resist=True, resist_attr="mente")])],
       img=IMG_DMG),
    # --------------------------------- VITAE ----------------------------
    _m("Curar", "vitae", "Ação", "Uma criatura", "", "Toque", "",
       "Você toca o alvo com as palmas das mãos cruzadas sobre ele e pronuncia vitae. Uma luz emana de suas mãos, fazendo com que o alvo sinta um conforto vindo delas e neutralizando a dor de seus ferimentos, enquanto eles se cicatrizam.\n\nEfeitos: Restaura 1 ponto de vida base do alvo e 1 ponto escalonado a cada 2 pontos acima de 10 no resultado da rolagem de Conjuração.\n\nMedicina concede +1 em Conjuração para esta conjuração.",
       "Restaura 2 pontos de vida base, em vez de 1 (apenas Círculo Intermediário) (-). Restaura 3 pontos de vida base, em vez de 1 (apenas Círculo Maior) (-). O alvo recebe regeneração até o fim da cena (apenas Círculo Maior) (-6). Não funciona em uma determinada raça de humanoide (+1). Só funciona em uma determinada raça de humanoide (+2). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       actions=[action("Curar (Conjuração vs 10 — cura 1 + escalonado)",
                       roll_attr="conjuracao", vs_difficulty=True, fixed_difficulty=10,
                       damage="-1", damage_type="", damage_resource="hp",
                       cost_mp=1)],
       img=IMG_HEAL),
    _m("Restaurar", "vitae", "Ação", "", "1m x Nível", "3m x Círculo x Nível", "",
       "Enquanto pronuncia a palavra vitae, você toca o solo em direção aos seus aliados, entrando em conexão com os mesmos e fazendo com que sua magia restaure suas condições físicas ou mentais.\n\nEfeitos: Você determina um tipo de condição física ou mental que esteja afetando um ou mais dos alvos. Essa condição é finalizada imediatamente.\n\nMedicina concede +1 em Conjuração para esta conjuração.",
       "Determine dois tipos de condições diferentes (apenas Círculo Intermediário ou Maior) (-4). Finaliza todas as condições negativas (apenas Círculo Maior) (-8). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       img=IMG_HEAL),
    _m("Reviver", "vitae", "Cena", "Uma criatura morta", "", "Toque", "",
       "Consumindo uma valiosa gema neste ritual arcano e pronunciando repetidamente a palavra vitae enquanto mantém contato físico com o alvo, você faz com que sua energia vital retorne a seu corpo.\n\nEfeitos: Você traz de volta à vida um alvo que tenha morrido há uma quantidade de dias igual ao seu nível. O alvo retorna com 1 ponto de vida. É necessário que o alvo tocado não tenha perdido nenhuma parte do corpo para que essa magia funcione.\n\nMedicina concede +1 em Conjuração para esta conjuração. Você precisa gastar 100.000 Vo em componentes especiais para realizar esta conjuração. Não há habilidade que possa anular a necessidade deles.",
       "Traz o alvo de volta à vida com metade dos pontos de vida (apenas Círculo Intermediário ou Maior) (-4). Traz o alvo de volta com todos os pontos de vida (apenas Círculo Maior) (-4). Traz o alvo de volta, mesmo que só haja parte do corpo dele (apenas Círculo Intermediário ou Maior) (-4). Traz o alvo de volta necessitando apenas de um objeto pessoal dele (apenas Círculo Maior) (-6). Traz de volta um alvo que tenha morrido há uma quantidade de semanas igual ao seu nível (apenas Círculo Intermediário ou Maior) (-4). Traz de volta um alvo que tenha morrido há uma quantidade de anos igual ao seu nível (apenas Círculo Maior) (-6). Necessita de componentes gestuais (apenas Círculo Menor) (+1). Necessita de componentes materiais ou foco (apenas Círculo Intermediário ou Menor) (+1).",
       img=IMG_HEAL),
]
