# -*- coding: utf-8 -*-
"""Habilidades — parte 2 (F–M). Fonte: Livro de Regras, Sessão 9."""
from builders import habilidade, effect, cost, action, applies
from data_habilidades_1 import IMG

IDIOMAS = [
    "Primordial", "Celestial", "Abissal", "Infernal", "Altarano", "Goblinóide",
    "Orc", "Anão", "Gigante", "Élfico", "Dracônico", "Gnomo", "Otherano",
    "Aisengardiano", "Eddano", "Aglaope Rúnico", "Sarunniano", "Sameriano",
    "Mistanni", "Código dos Ladrões",
]

HABILIDADES_2 = [
    habilidade(
        "Familiar",
        "Celestial, draconiano, infernal, bruxo e mago",
        "Você tem uma criatura como aliado, que pode se comunicar magicamente com você. A criatura deve ter o traço Familiar e Desafio igual ou menor ao seu nível. Você recebe o benefício garantido pelo traço Familiar do seu familiar escolhido. Você também pode usar sua ação para ordenar o familiar a atacar ou o seu movimento para ordená-lo a se deslocar.",
        "Independente da criatura escolhida como seu familiar, ela agora possui Mente 3, caso o atributo de Mente da versão original da criatura seja menor. Você pode conjurar magias usando a posição do seu familiar como posição do conjurador, em vez da sua própria.",
        20, 40,
        img=IMG["fera"],
    ),
    habilidade(
        "Ferocidade Primitiva",
        "Terras de Beoven",
        "Você recebe 1 ponto de Proteção contra frio. Adicionalmente, se você se deslocar 4m ou mais em linha reta na direção de uma criatura e realizar um ataque corpo a corpo contra ela logo após se deslocar, seu ataque recebe uma penalidade de -2 e um bônus de dano igual ao seu nível.",
        "Você recebe 2 pontos de Proteção contra frio, em vez de 1. O ataque recebe uma penalidade de -1, em vez de -2.",
        10, 30,
        effects=[
            effect("rd", "all", 1, level="B", label="Ferocidade B: Proteção 1 (frio)", damage_type="frio"),
            effect("rd", "all", 1, level="A", label="Ferocidade A: +1 Proteção (frio, total 2)", damage_type="frio"),
        ],
        img=IMG["combate"],
    ),
    habilidade(
        "Firmeza Física",
        "Anão das montanhas e anão das terras baixas",
        "Você recebe 1D em rolagens para evitar ser derrubado ou movido involuntariamente. Seus pontos de vida aumentam em 1 ponto.",
        "Quando uma criatura adjacente tentar derrubá-lo ou movê-lo, você pode gastar 1 ponto heróico para evitar automaticamente e usar sua reação para realizar um ataque contra ela. Seus pontos de vida aumentam em 3 pontos (em vez de 1). Adicionalmente, você recebe um bônus igual a metade do seu nível em rolagens para resistir e anular condições de Agarrado, Enfraquecido, Exausto e Paralisado.",
        10, 30,
        effects=[
            effect("stat", "hp", 1, level="B", label="Firmeza Física B: +1 PV"),
            effect("stat", "hp", 2, level="A", label="Firmeza Física A: +2 PV (total +3)"),
        ],
        img=IMG["corpo"],
    ),
    habilidade(
        "Forma Animal",
        "Druida",
        "Você pode usar sua ação rápida e gastar 1 ponto de magia para se transformar em uma criatura do tipo Fera cujo Desafio seja igual a seu Nível x2. A transformação dura uma cena e altera todas as suas características exceto sua Mente e seus pontos de magia. A nova forma recebe, adicionalmente, 1D em Força ou Agilidade. Todo o dano sofrido na forma animal permanece quando você retorna à sua forma original.",
        "Quando você se transforma usando essa habilidade, você recebe um dos seguintes benefícios: 1D em Percepção; +3m de Deslocamento; Proteção 2 contra Corte, Perfuração e Concussão; Bônus de ataque +2.",
        20, 40,
        mode="active", activation="Ação rápida",
        costs=[cost("mp", 1, "Transformar (dura uma cena)")],
        img=IMG["fera"],
    ),
    habilidade(
        "Força Repentina",
        "Dunas do Norte",
        "Quando corre risco de vida, você adquire força e resistência enormes. Sempre que chegar a uma quantidade de pontos de vida igual ao seu nível, você recebe 1D nas rolagens de Força ou Agilidade até o fim da cena e 2 pontos de sobrevida.",
        "Você recebe 2D nas rolagens de Força ou Agilidade, em vez de 1D, e recebe 4 pontos de sobrevida, em vez de 2.",
        10, 30,
        img=IMG["corpo"],
    ),
    habilidade(
        "Fúria",
        "Bárbaro",
        "Você pode escolher entrar em fúria durante seu turno, gastando 1 ponto heróico. Enquanto estiver em fúria, você recebe 1D em Força, Sobrevida e Proteção contra Corte, Perfuração e Concussão igual a metade do seu nível (arredondado para cima), mas perde 1D em todas as suas rolagens de Mente. A fúria dura uma quantidade de rodadas igual ao seu Vigor. Quando a Fúria acaba, você fica exausto até o fim da cena (Não anula).",
        "A fúria te dá Sobrevida e Proteção contra Corte, Perfuração e Concussão igual ao seu nível. A fúria dura agora até o fim da cena. Quando ela acaba, você não fica exausto. Enquanto estiver em fúria, você pode gastar um ponto heróico quando fizer um ataque corpo a corpo, para trocar o resultado de um dos dados por um 6.",
        20, 40,
        mode="active", activation="Livre (no seu turno)",
        costs=[cost("heroic", 1, "Entrar em fúria")],
        effects=[
            effect("dice", "forca", 1, level="B", label="Fúria: 1D Força"),
            effect("dice", "mente", -1, level="B", label="Fúria: -1D Mente"),
        ],
        img=IMG["combate"],
    ),
    habilidade(
        "Furtividade",
        "Elfo da floresta, elfo das profundezas, gnomo das profundezas, pequenino, infernal, ladino, monge, patrulheiro, clérigo (Krimmena, Meriak, Illain e Mizra)",
        "Você recebe 1D em ações furtivas (esconder-se, andar em silêncio, punga...). Você pode mover-se o seu deslocamento normalmente enquanto tenta fazer silêncio.",
        "Mesmo que você use sua ação para correr, ainda pode caminhar em silêncio. Você também pode usar sua ação de movimento para realizar uma finta (Agilidade oposta a Percepção) contra um alvo adjacente, deixando-o indefeso até o começo do turno dele.",
        10, 30,
        activation="Movimento (finta, nível A)",
        actions=[action("Finta (A): Agilidade vs Percepção — alvo indefeso",
                        roll_attr="agilidade", defense_attr="percepcao",
                        applies_effects=[applies("Indefeso (até o começo do turno do alvo)",
                                                 fx_type="condition", fx_target="indefeso",
                                                 duration_mode="rounds", duration_rounds=1)])],
        img=IMG["pericia"],
    ),
    habilidade(
        "Garras",
        "Infernal",
        "Você desenvolveu garras que podem ser usadas como armas. Suas garras são consideradas uma arma natural, cujo ataque usa a Força ou Agilidade e causam dano de Garras +Nível.",
        "Quando você ataca com suas garras e acerta, você pode gastar 1 ponto heróico para causar dano contínuo de sangramento ou tornar o ataque um acerto crítico.",
        20, 40,
        activation="Ação (ataque)",
        actions=[action("Ataque de Garras (dano = Corte +Nível; ajuste o valor)",
                        roll_attr="forca", damage="1", damage_type="corte",
                        defense_attr="esquiva", defense_attr2="bloqueio")],
        img=IMG["combate"],
    ),
    habilidade(
        "Golpe Cegante",
        "Ladino",
        "Quando você faz um ataque corpo a corpo e acerta, você pode gastar 1 ponto heróico para deixar o alvo cego pelo resto da cena (Percepção anula).",
        "O alvo fica cego até que receba cuidados médicos.",
        20, 40,
        activation="Ação (ataque)",
        actions=[action("Golpe Cegante (junto a um ataque corpo a corpo)",
                        roll_attr="forca", cost_heroic=1,
                        applies_effects=[applies("Cego (Percepção anula)", fx_type="condition",
                                                 fx_target="cego", duration_mode="scene",
                                                 resist=True, resist_attr="percepcao")])],
        img=IMG["combate"],
    ),
    habilidade(
        "Golpe Crítico Brutal",
        "Bárbaro",
        "Quando você acerta um golpe crítico com uma arma corpo a corpo, você pode gastar 1 ponto heróico para causar pontos de dano final adicionais igual a metade da sua Força.",
        "Quando você acerta um golpe crítico com uma arma corpo a corpo, você pode gastar 1 ponto heróico para causar pontos de dano final adicionais igual à sua Força.",
        20, 40, prereq="Força 4+",
        img=IMG["combate"],
    ),
    habilidade(
        "Golpe de Sorte",
        "Gnomo da floresta e ladino",
        "Uma vez por cena, você pode escolher ser bem sucedido em um ataque, superando a defesa do alvo por 2 pontos de diferença.",
        "Quando ataca, você pode gastar 1 ponto heróico para que seu resultado neste ataque seja um 12 natural (um acerto crítico).",
        20, 40,
        img=IMG["combate"],
    ),
    habilidade(
        "Golpear com Escudo",
        "Guardião, guerreiro e paladino",
        "Você pode gastar seu movimento para realizar um ataque com escudo (rolagem de Força, dano igual a Concussão +0).",
        "Se você atacar com escudo e causar pelo menos 2 pontos de dano ou mais, o alvo fica pasmo (Vigor anula). A dificuldade na rolagem de Vigor é igual a 10 + o dano final causado com o escudo.",
        20, 40,
        activation="Movimento",
        actions=[action("Ataque com Escudo (Concussão +0)",
                        roll_attr="forca", damage="0", damage_type="concussao",
                        defense_attr="esquiva", defense_attr2="bloqueio")],
        img=IMG["combate"],
    ),
    habilidade(
        "Grito de Guerra",
        "Orc, bárbaro, paladino, clérigo (Garlock, Vargoth e Grumbar)",
        "Usando sua ação rápida, você pode dar um grito que concede 1D nas rolagens de ataque a todos os aliados que possam ouvi-lo, pelo resto da cena ou até que você chegue a 0 pontos de vida.",
        "Quando você usa seu grito de guerra, todos os inimigos que puderem ouvi-lo devem ser bem sucedidos em uma rolagem de Mente oposta ao seu Vigor para não ficarem abalados até o fim da cena (Mente Difícil anula) ou até que você chegue a 0 pontos de vida. Essa habilidade não funciona contra inimigos que tenham mais pontos heróicos que você, nem contra inimigos surdos.",
        20, 40, prereq="Mente 4+",
        activation="Ação rápida",
        actions=[
            action("Grito de Guerra: 1D ataque aos aliados (cena)",
                   can_roll=False, target_mode="aura", area=20,
                   applies_effects=[applies("Grito de Guerra: 1D em ataques", fx_type="dice",
                                            fx_target="attack", fx_value=1, duration_mode="scene")]),
            action("Grito de Guerra (A): amedrontar inimigos (Vigor vs Mente)",
                   roll_attr="vigor", target_mode="aura", area=20, defense_attr="mente",
                   applies_effects=[applies("Abalado (Mente Difícil anula)", fx_type="condition",
                                            fx_target="abalado", duration_mode="scene",
                                            resist=True, resist_attr="mente")]),
        ],
        img=IMG["combate"],
    ),
    habilidade(
        "Guerra Santa",
        "Clérigo e paladino",
        "Você recebe 1D em rolagens de conhecimento e investigação relacionadas a servos de religiões rivais à sua.",
        "Você recebe 1D em suas rolagens de ataque e defesa contra servos de religiões opostas à sua. Quando você usar algum poder divino, você pode gastar 1 ponto heróico para que servos de religiões rivais que possam vê-lo ajoelhem-se, ficando pasmos (Mente anula) até o fim da cena e indefesos até o começo do turno deles.",
        10, 30,
        img=IMG["social"],
    ),
    habilidade(
        "Guerreiro da Fé",
        "Clérigo",
        "Você pode usar a Aura Divina dos Aspectos da sua divindade, a que você tem acesso.",
        "Você pode usar o Servo Divino dos Aspectos da sua divindade, a que você tem acesso.",
        20, 40, prereq="Primeiro Aspecto",
        img=IMG["social"],
    ),
    habilidade(
        "Guerreiro Incauto",
        "Meio-orc, orc e bárbaro",
        "Você pode escolher ficar indefeso até o começo do seu próximo turno, para receber 1D em suas rolagens de ataque corpo a corpo pela duração da condição.",
        "Seus ataques causam 2 pontos de dano adicionais, enquanto estiver indefeso dessa forma.",
        10, 30,
        img=IMG["combate"],
    ),
    habilidade(
        "Guia Divino",
        "Clérigo",
        "Quando você gasta 1 ponto heróico para re-rolar uma rolagem que você fez, você recebe 1D nessa nova rolagem.",
        "Quando você gasta 1 ponto heróico para re-rolar uma rolagem que você fez, você recebe também +2 nesta rolagem. Adicionalmente, sempre que gastar pontos heróicos, role um dado para cada um. Em um resultado 6, você recupera o ponto heróico gasto.",
        10, 30, prereq="Primeiro Aspecto",
        img=IMG["social"],
    ),
    *[
        habilidade(
            f"Idioma Adicional ({idioma})",
            "Humano, meio-elfo, celestial, draconiano, entrópico, infernal, bardo e ladino.",
            f"Você é capaz de falar, ler e escrever o idioma {idioma}.",
            "—",
            5, 0,
            img=IMG["pericia"],
        )
        for idioma in IDIOMAS
    ],
    habilidade(
        "Implacável",
        "Durathor",
        "Seu limite de carga aumenta em 2 pontos. Adicionalmente, quando você realiza um ataque corpo a corpo e acerta, você empurra o alvo uma quantidade de metros igual ao dano escalonado causado. Um alvo empurrado mais de 4m dessa forma ficará caído. Você recebe +1 em rolagens para evitar ser movido, puxado, empurrado ou derrubado.",
        "Seu limite de carga aumenta em 4 pontos, em vez de 2. Um alvo empurrado mais de 2m dessa forma ficará caído. Você recebe +2 em rolagens para evitar ser movido, puxado, empurrado ou derrubado, em vez de +1.",
        10, 30,
        img=IMG["corpo"],
    ),
    habilidade(
        "Implemento Arcano Superior",
        "Mago",
        "Você pode usar como foco um objeto de valor emocional (exceto armas), no lugar do foco padrão. Você pode encantá-lo com propriedades de outros focos.",
        "Seu foco pode ser uma arma ou qualquer outro item que você possa empunhar.",
        10, 30,
        img=IMG["magia"],
    ),
    habilidade(
        "Ímpeto",
        "Meio-orc, bárbaro, guardião, guerreiro e paladino",
        "Quando você fica com 0 pontos de vida, você pode usar sua reação para recuperar pontos de vida igual a metade do seu nível e continuar de pé. Você pode usar essa habilidade uma vez por dia.",
        "Você pode usar essa habilidade uma vez por cena. Você recupera pontos de vida igual ao seu nível.",
        20, 40, prereq="Vigor 4+",
        activation="Reação",
        img=IMG["corpo"],
    ),
    habilidade(
        "Impulso de Combate",
        "Guerreiro",
        "Quando você ataca com uma arma corpo a corpo, você pode gastar 1 ponto heróico para fazer uma quantidade de ataques adicionais igual a metade dos pontos heróicos gastos desde seu último descanso (arredondado para cima).",
        "Quando você usa essa habilidade, seus ataques extras recebem um bônus no dano base igual à quantidade de criaturas abatidas por você neste turno. Quando você usa seu movimento para se deslocar, você pode dividir seu Deslocamento entre os ataques.",
        20, 40,
        img=IMG["combate"],
    ),
    habilidade(
        "Inspirar",
        "Bardo",
        "Você pode usar sua ação para realizar uma performance (cantar, recitar um poema, tocar uma música) e inspirar seus aliados. Cada aliado que puder ouvi-lo recebe 1D para uma rolagem realizada no próximo turno deles.",
        "Seus aliados recebem 2D (em vez de 1D), que podem ser gastos numa mesma rolagem ou em rolagens diferentes, à escolha do alvo.",
        20, 40,
        activation="Ação",
        actions=[action("Inspirar: 1D aos aliados (próximo turno)",
                        can_roll=False, target_mode="aura", area=20,
                        applies_effects=[applies("Inspirado: 1D em uma rolagem", fx_type="dice",
                                                 fx_target="all", fx_value=1,
                                                 duration_mode="rounds", duration_rounds=1)])],
        img=IMG["social"],
    ),
]

# --- Juramentos (Paladino) — cada juramento é uma habilidade própria -----
_JURAMENTO_BASE = (
    "Escolha um juramento quando comprar esta habilidade. Ao cumprir com um dever do seu "
    "Juramento escolhido, você recebe 1 Ponto de Juramento e recebe favores de acordo com os "
    "pontos acumulados. Esses pontos diminuem em 1 quando você descansa."
)
_JURAMENTO_AVANCADO = (
    "Enquanto você tiver 3 Pontos de Juramento ou mais, você emana uma aura com raio igual à "
    "quantidade de Pontos de Juramento. Aliados dentro da aura recebem 1D em rolagens de defesa. "
    "Enquanto você tiver 5 Pontos de Juramento ou mais, aliados dentro da aura recebem também 1D "
    "em rolagens de ataque. Enquanto você emanar essa aura, você e aliados dentro dela ficam "
    "imunes à condição de Abalado."
)

HABILIDADES_2 += [
    habilidade(
        "Juramento (Devoção)",
        "Paladino",
        _JURAMENTO_BASE + "\n\nDeveres — Proteja os Indefesos: sofrer dano de um ataque inimigo enquanto estiver adjacente a um aliado. Salve da Morte: curar um aliado morrendo. Vida de Devoção: conceder uma condição benéfica a um aliado.\n\nFavores — 1 Ponto: você recebe 1D em rolagens de cuidados médicos. 2 Pontos: você recupera pontos de vida igual ao seu Nível quando cura um aliado. 3 Pontos: você recebe um bônus em Conjuração igual a metade do seu Nível. 4 Pontos: você recebe sobrevida igual ao seu Nível sempre que gastar um ponto heróico para re-rolar uma defesa. 5 Pontos: você recebe regeneração sempre que chega a 1 ponto de vida.",
        _JURAMENTO_AVANCADO,
        20, 40,
        img=IMG["social"],
    ),
    habilidade(
        "Juramento (Justiça)",
        "Paladino",
        _JURAMENTO_BASE + "\n\nDeveres — Lute com Honra: eliminar um inimigo enquanto não tiver nenhum aliado adjacente a ele. Pague com a Mesma Moeda: acertar um golpe em um inimigo usando sua reação. Punho da Justiça: acertar um golpe crítico em um inimigo que tiver ferido um aliado no mesmo combate.\n\nFavores — 1 Ponto: você recebe 1D em rolagens para notar mentiras. 2 Pontos: você recupera pontos de vida igual ao seu Nível quando elimina um inimigo. 3 Pontos: você recebe um bônus igual a metade do seu Nível nos seus ataques enquanto estiver com metade dos pontos de vida ou menos. 4 Pontos: você recebe sobrevida igual aos seus pontos de Juramento sempre que gastar um ponto heróico para re-rolar uma defesa. 5 Pontos: enquanto estiver com metade dos pontos de vida ou menos, todo o seu dano causado será considerado dano final.",
        _JURAMENTO_AVANCADO,
        20, 40,
        img=IMG["social"],
    ),
    habilidade(
        "Juramento (Vingança)",
        "Paladino",
        _JURAMENTO_BASE + "\n\nDeveres — Elimine os Inimigos: causar dano a um inimigo deixando-o com 0 pontos de vida. Sem Piedade: acertar um golpe crítico em um inimigo. Assista-os Perecer: causar dano contínuo a um inimigo.\n\nFavores — 1 Ponto: você recebe 1D em rolagens de Percepção para rastrear inimigos. 2 Pontos: você recupera pontos de vida igual ao seu Nível quando elimina um inimigo. 3 Pontos: você recebe um bônus igual a metade do seu nível nos seus ataques concedidos por manobras. 4 Pontos: você recebe sobrevida igual ao seu Nível sempre que gastar um ponto heróico para re-rolar um ataque. 5 Pontos: quando um inimigo sofre dano de um de seus ataques com arma, ele também sofre dano contínuo de sangramento.",
        _JURAMENTO_AVANCADO,
        20, 40,
        img=IMG["social"],
    ),
    habilidade(
        "Lábia Natural",
        "Faen Leste",
        "Você recebe 1D em rolagens de interação social. Adicionalmente, você pode reduzir a quantidade de dias necessários para encontrar itens mágicos à venda em um quarto.",
        "Você pode re-rolar todos os dados com resultado 1 e 2 em rolagens de interação social, até obter um resultado maior. Você reduz um terço, em vez de um quarto dos dias.",
        10, 30,
        img=IMG["social"],
    ),
    habilidade(
        "Letalidade",
        "Ladino",
        "Seus ataques bem sucedidos com armas de Artilharia, Lâminas Pequenas ou Leves a alvos indefesos ou surpresos causam dano final adicional igual à metade do seu nível (arredondado para cima).",
        "Seus ataques bem sucedidos com armas de Artilharia, Lâminas Pequenas ou Leves a alvos indefesos ou surpresos causam dano final adicional igual ao seu nível.",
        20, 40, prereq="Agilidade 4+",
        img=IMG["combate"],
    ),
    habilidade(
        "Lidar com Animais",
        "Gnomo da floresta, bardo, druida e patrulheiro",
        "Você recebe 1D em rolagens para lidar com criaturas do tipo Fera (cativar, afugentar, adestrar, rastrear...). Você pode adestrar uma criatura do tipo Fera com o traço Montaria e Desafio igual ao seu nível.",
        "Você pode gastar 1 ponto heróico para se comunicar com uma criatura do tipo Fera através de pequenos gestos e sons. Você pode adestrar montarias que não sejam do tipo Fera.",
        10, 30,
        img=IMG["fera"],
    ),
    habilidade(
        "Lidar com Armadilhas",
        "Gnomo das rochas e ladino",
        "Você recebe 1D em rolagens para lidar com armadilhas (notar, desarmar, escapar...) e leva apenas 10 minutos para prepará-las.",
        "Você leva apenas 1 minuto para preparar uma armadilha. Você gasta um terço a menos do valor da armadilha.",
        10, 30,
        img=IMG["pericia"],
    ),
    habilidade(
        "Linguista Arcano",
        "Bruxo e mago",
        "Você consegue ler em qualquer idioma.",
        "Você consegue identificar runas arcanas e palavras arcanas que não conheça, sem nenhuma rolagem.",
        10, 30,
        img=IMG["magia"],
    ),
    habilidade(
        "Magia Sem Gestos",
        "Bruxo",
        "Você pode conjurar magias de círculo intermediário ou maior sem a necessidade de componentes gestuais. Uma magia conjurada sem gestos custa 1 ponto de magia adicional para ser conjurada.",
        "Você pode conjurar uma magia sem gestos, sem pagar 1 ponto de magia adicional.",
        10, 30,
        img=IMG["magia"],
    ),
    habilidade(
        "Magia Sem Materiais",
        "Bruxo",
        "Você pode conjurar magias de círculo maior sem a necessidade de bolsa de componentes ou de um foco. Uma magia conjurada sem os componentes materiais custa 1 ponto de magia adicional para ser conjurada.",
        "Você pode conjurar uma magia sem componentes materiais comuns, sem pagar 1 ponto de magia adicional.",
        10, 30,
        img=IMG["magia"],
    ),
    habilidade(
        "Magia Silenciosa",
        "Bruxo",
        "Você pode conjurar magias sem a necessidade de componentes verbais. Uma magia conjurada sem os componentes verbais custa 1 ponto de magia adicional para ser conjurada.",
        "Você pode conjurar uma magia sem componentes verbais, sem pagar 1 ponto de magia adicional.",
        10, 30,
        img=IMG["magia"],
    ),
    habilidade(
        "Magia Unilateral",
        "Clérigo e druida",
        "Quando você conjura uma magia de área, você pode escolher uma quantidade de aliados dentro da área igual ao seu nível. Os aliados escolhidos não serão afetados pela magia.",
        "Quando você conjura uma magia de área, ela não afeta nenhum aliado dentro da área.",
        20, 40,
        img=IMG["magia"],
    ),
    habilidade(
        "Marca da Mácula",
        "Casa Norn",
        "Você é imune a doenças e envenenamento. Você também recebe proteção contra dano necrótico e de veneno igual à metade do seu nível. A fama do seu povo de \"mortos andantes\" lhe concede 1D em rolagens de intimidação. Adicionalmente, inimigos que impuserem a você qualquer condição negativa sofrerão dano contínuo necrótico até o fim da cena (Vigor anula).",
        "O dano necrótico contínuo dura até que uma magia o cancele.",
        10, 30,
        img=IMG["corpo"],
    ),
    habilidade(
        "Medicina",
        "Bárbaro, bardo, clérigo, druida, guardião, guerreiro, mago, monge, paladino e patrulheiro.",
        "Você recebe 1D em rolagens para prestar cuidados médicos, diagnosticar ou realizar tratamento intensivo para outros personagens. Você pode gastar 1 ponto heróico para criar 1 frasco de remédio por nível, durante seu descanso.",
        "Suas rolagens bem sucedidas para prestar cuidados médicos e seus remédios curam 2 pontos de vida, em vez de 1.",
        10, 30,
        img=IMG["pericia"],
    ),
    *[
        habilidade(
            f"Melhorar Atributo ({attr_nome})",
            "Draconiano, infernal e todas as vocações.",
            f"Você recebe 1D no atributo {attr_nome}.",
            "—",
            40, 0,
            effects=[effect("dice", attr_key, 1, level="B", label=f"Melhorar Atributo: 1D {attr_nome}")],
            img=IMG["corpo"],
        )
        for attr_nome, attr_key in [
            ("Força", "forca"), ("Agilidade", "agilidade"), ("Vigor", "vigor"),
            ("Mente", "mente"), ("Percepção", "percepcao"),
        ]
    ],
    habilidade(
        "Mercado Negro",
        "Elfo das profundezas, gnomo das profundezas, infernal, bardo, bruxo e ladino.",
        "Você pode realizar uma rolagem para obter informações sobre mercados proibidos da cidade. Sendo bem sucedido, você sabe onde adquirir itens comuns pagando um terço a menos do valor de venda. Sempre que você gastar seus dias de inatividade procurando por itens mágicos em uma cidade, subtraia seu nível da quantidade de dias necessários para encontrar.",
        "Você consegue comprar itens comuns por metade do preço (em vez de um terço a menos). Sempre que você gastar seus dias de inatividade procurando por itens mágicos em uma cidade, subtraia o dobro do seu nível da quantidade de dias necessários para encontrar.",
        20, 40, prereq="Mente 4+",
        img=IMG["social"],
    ),
    habilidade(
        "Mestre do Conhecimento",
        "Bardo",
        "Você recebe 1D em rolagens de conhecimento.",
        "Você recebe 2D em rolagens de conhecimento (em vez de 1D).",
        20, 40,
        img=IMG["pericia"],
    ),
    habilidade(
        "Montar Criatura",
        "Gnomo da floresta, bárbaro, bardo, druida, guardião, guerreiro, paladino e patrulheiro.",
        "Você recebe 1D em rolagens para montar uma criatura ou para se manter montado. Você pode atacar enquanto estiver montado. Você pode usar sua ação rápida para comandar sua montaria a realizar uma Ação de Montaria.",
        "Você pode comandar sua montaria a usar sua Ação de Montaria usando uma ação livre em vez de sua ação rápida.",
        10, 30,
        img=IMG["fera"],
    ),
    habilidade(
        "Morte Antes da Desonra",
        "Sei Yang",
        "Sempre que um combate se inicia, você pode apostar sua vida nele. Se o fizer, você receberá 3 pontos de dano final adicional de qualquer ataque ou magia, mas seus ataques e magias causarão 2 pontos de dano final adicionais.",
        "O dano final recebido é igual a 2 (em vez de 3). O dano final causado é igual a 3 (em vez de 2).",
        10, 30,
        img=IMG["combate"],
    ),
    habilidade(
        "Movimento Astuto",
        "Gnomo das profundezas e ladino",
        "Enquanto você estiver escondido, você pode mover metade do seu Deslocamento e ainda continuar escondido sem ter que realizar uma nova rolagem. Você deve estar sob cobertura ao fim desse movimento.",
        "Quando usa essa habilidade, você pode mover todo o seu Deslocamento em vez de apenas metade.",
        10, 30,
        img=IMG["pericia"],
    ),
    habilidade(
        "Movimento de Natação",
        "Clérigo (Neidar)",
        "Usando seu movimento, você pode se deslocar em águas calmas com a mesma habilidade com que se desloca em solo, sem a necessidade de nenhuma rolagem para se deslocar.",
        "Quando você se desloca em ambientes aquáticos, você não fica lento. Adicionalmente, você não precisa realizar rolagens quando se desloca em águas agitadas.",
        10, 30,
        img=IMG["corpo"],
    ),
]
