# -*- coding: utf-8 -*-
"""Equipamentos. Fonte: Livro de Regras, Sessão 10."""
from builders import equipamento, effect, action

IMG_ARMOR = "icons/svg/shield.svg"
IMG_WEAPON = "icons/svg/sword.svg"
IMG_TOOL = "icons/svg/anchor.svg"
IMG_ITEM = "icons/svg/item-bag.svg"
IMG_MOUNT = "icons/svg/pawprint.svg"
IMG_SERVICE = "icons/svg/coins.svg"


def _armadura(nome, preco, cat, prot, peso, pen, desc, props="-"):
    effs = [
        effect("rd", "all", prot, label=f"{nome}: Proteção {prot} (corte)", damage_type="corte"),
        effect("rd", "all", prot, label=f"{nome}: Proteção {prot} (perfuração)", damage_type="perfuracao"),
        effect("rd", "all", prot, label=f"{nome}: Proteção {prot} (concussão)", damage_type="concussao"),
    ]
    if pen:
        effs += [
            effect("bonus", "esquiva", -pen, label=f"{nome}: penalidade -{pen} Esquiva"),
            effect("bonus", "conjuracao", -pen, label=f"{nome}: penalidade -{pen} Conjuração"),
        ]
    return equipamento(
        nome, cat, preco, peso,
        desc + f"\n\nProteção: Corte, Perfuração e Concussão {prot}. Penalidade: -{pen} (atividades atléticas, acrobáticas, Conjuração e Esquiva). Propriedade: {props}",
        notes=f"Penalidade -{pen}",
        mode="active", effects=effs, img=IMG_ARMOR,
    )


def _arma(nome, preco, grupo, ataque, dano, dtipo, peso, props, alcance=0, versatil=False, desc=""):
    roll_attr = "agilidade" if ataque == "Agilidade" else "forca"
    acts = [action(
        f"Ataque — {nome}",
        roll_attr=roll_attr, damage=str(dano), damage_type=dtipo,
        defense_attr="esquiva", defense_attr2="bloqueio", rng=alcance,
    )]
    if versatil:
        acts.append(action(
            f"Ataque — {nome} (duas mãos, +1 dano)",
            roll_attr=roll_attr, damage=str(dano + 1), damage_type=dtipo,
            defense_attr="esquiva", defense_attr2="bloqueio", rng=alcance,
        ))
    tipo_label = {"corte": "Corte", "perfuracao": "Perfuração", "concussao": "Concussão"}[dtipo]
    body = (desc + "\n\n" if desc else "") + (
        f"Grupo: {grupo}. Ataque: {ataque}. Dano Base: {tipo_label} +{dano}. "
        f"Propriedades: {props}."
    )
    return equipamento(
        nome, f"Arma ({grupo})", preco, peso, body,
        notes=props, actions=acts, img=IMG_WEAPON,
    )


EQUIPAMENTOS = [
    # ------------------------------ Armaduras ---------------------------
    _armadura("Armadura de Couro", "25 Vo", "Armadura Leve", 1, 1, 1,
              "Armadura feita de peças de couro firmemente costuradas com cânhamo ou outro tipo de costura durável."),
    _armadura("Armadura de Peles", "60 Vo", "Armadura Leve", 2, 1, 2,
              "Armadura feita de peles grossas e pesadas de animais, curtidas e batidas."),
    _armadura("Cota de Malha", "50 Vo", "Armadura Pesada", 2, 2, 2,
              "Armadura feita de anéis metálicos entrelaçados em um tecido de aço."),
    _armadura("Armadura de Escamas", "40 Vo", "Armadura Pesada", 2, 2, 3,
              "Armadura composta de peças sobrepostas de material extremamente durável, como aço ou mesmo escamas de dragão.",
              props="Barulhenta (a penalidade também é aplicada em rolagens para caminhar silenciosamente)."),
    _armadura("Armadura de Placas", "75 Vo", "Armadura Pesada", 3, 3, 4,
              "Armadura feita de placas pesadas moldadas de metal ou outro material igualmente resistente.",
              props="Barulhenta (a penalidade também é aplicada em rolagens para caminhar silenciosamente)."),
    # ------------------------------ Armas -------------------------------
    _arma("Adaga", "1 Vo", "Lâminas Pequenas", "Força ou Agilidade", 1, "perfuracao", 0,
          "Simples, Uma Mão, Arremesso, Corpo a Corpo, Leve, Alcance 5m", alcance=5),
    _arma("Alabarda", "25 Vo", "Lanças", "Força", 4, "corte", 1,
          "Militar, Duas Mãos, Haste, Corpo a Corpo"),
    _arma("Arco Curto", "12 Vo", "Arcos", "Agilidade", 2, "perfuracao", 0,
          "Simples, Duas Mãos, Artilharia, Alcance 15m", alcance=15),
    _arma("Arco Longo", "60 Vo", "Arcos", "Agilidade", 3, "perfuracao", 0,
          "Militar, Duas Mãos, Artilharia, Alcance 45m", alcance=45),
    _arma("Ataque Desarmado", "—", "Desarmado", "Força", 0, "concussao", 0,
          "Simples, Corpo a Corpo"),
    _arma("Azagaia", "4 Vo", "Lanças", "Força", 2, "perfuracao", 0,
          "Simples, Uma Mão, Arremesso, Alcance 5m", alcance=5),
    _arma("Besta de Mão", "19 Vo", "Bestas", "Agilidade", 2, "perfuracao", 0,
          "Militar, Uma Mão, Artilharia, Alcance 10m, Recarga, Leve", alcance=10),
    _arma("Besta Leve", "17 Vo", "Bestas", "Agilidade", 3, "perfuracao", 0,
          "Simples, Duas Mãos, Artilharia, Alcance 15m, Recarga", alcance=15),
    _arma("Besta Pesada", "45 Vo", "Bestas", "Agilidade", 4, "perfuracao", 1,
          "Militar, Duas Mãos, Artilharia, Alcance 30m, Recarga", alcance=30),
    _arma("Bordão", "2 Va", "Cajados", "Força", 2, "concussao", 0,
          "Simples, Versátil, Corpo a Corpo", versatil=True),
    _arma("Chicote Longo", "18 Vo", "Chicotes", "Força e Agilidade", 1, "corte", 0,
          "Militar, Uma Mão, Haste, Corpo a Corpo"),
    _arma("Cimitarra", "19 Vo", "Lâminas Pequenas", "Força ou Agilidade", 2, "corte", 0,
          "Militar, Uma Mão, Leve, Corpo a Corpo"),
    _arma("Clava", "1 Va", "Maças", "Força", 1, "concussao", 0,
          "Simples, Uma Mão, Leve, Corpo a Corpo"),
    _arma("Clava Grande", "1 Vo", "Maças", "Força", 3, "concussao", 1,
          "Simples, Duas Mãos, Corpo a Corpo"),
    _arma("Dardo", "1 Va", "Dardos", "Agilidade", 1, "perfuracao", 0,
          "Simples, Uma Mão, Arremesso, Alcance 5m", alcance=5),
    _arma("Espada Curta", "19 Vo", "Lâminas Pequenas", "Força ou Agilidade", 2, "corte", 0,
          "Militar, Uma Mão, Corpo a Corpo, Leve"),
    _arma("Espada Grande", "28 Vo", "Lâminas Grandes", "Força", 5, "corte", 2,
          "Militar, Duas Mãos, Corpo a Corpo"),
    _arma("Espada Longa", "24 Vo", "Lâminas Grandes", "Força", 3, "corte", 0,
          "Militar, Versátil, Corpo a Corpo", versatil=True),
    _arma("Florete", "27 Vo", "Lâminas Pequenas", "Força ou Agilidade", 3, "perfuracao", 0,
          "Militar, Uma Mão, Corpo a Corpo"),
    _arma("Foice Curta", "3 Vo", "Lâminas Pequenas", "Força ou Agilidade", 1, "corte", 0,
          "Simples, Uma Mão, Corpo a Corpo, Leve"),
    _arma("Foice Longa", "5 Vo", "Lâminas Grandes", "Força ou Agilidade", 2, "corte", 0,
          "Simples, Duas Mãos, Corpo a Corpo, Haste"),
    _arma("Funda", "3 Vo", "Fundas", "Agilidade", 1, "concussao", 0,
          "Simples, Uma Mão, Artilharia, Alcance 5m", alcance=5),
    _arma("Glaive", "5 Vo", "Lanças", "Força", 4, "corte", 1,
          "Militar, Duas Mãos, Corpo a Corpo, Haste"),
    _arma("Lança Curta", "5 Vo", "Lanças", "Força", 2, "perfuracao", 1,
          "Militar, Versátil, Corpo a Corpo, Arremesso, Alcance 5m", alcance=5, versatil=True),
    _arma("Lança Longa", "33 Vo", "Lanças", "Força", 5, "perfuracao", 2,
          "Militar, Duas Mãos, Corpo a Corpo, Haste"),
    _arma("Maça", "2 Vo", "Maças", "Força", 2, "concussao", 0,
          "Simples, Uma Mão, Corpo a Corpo"),
    _arma("Maça Estrela", "17 Vo", "Maças", "Força", 3, "concussao", 0,
          "Militar, Uma Mão, Corpo a Corpo"),
    _arma("Machado de Batalha", "24 Vo", "Machados", "Força", 3, "corte", 0,
          "Militar, Versátil, Corpo a Corpo", versatil=True),
    _arma("Machado de Mão", "3 Vo", "Machados", "Força", 2, "corte", 0,
          "Simples, Uma Mão, Corpo a Corpo, Arremesso, Alcance 5m", alcance=5),
    _arma("Machado Grande", "28 Vo", "Machados", "Força", 5, "corte", 2,
          "Militar, Duas Mãos, Corpo a Corpo"),
    _arma("Malho", "28 Vo", "Martelos", "Força", 5, "concussao", 2,
          "Militar, Duas Mãos, Corpo a Corpo"),
    _arma("Mangual", "17 Vo", "Manguais", "Força", 3, "concussao", 0,
          "Militar, Uma Mão, Corpo a Corpo"),
    _arma("Martelo de Arremesso", "3 Vn", "Martelos", "Força", 1, "concussao", 0,
          "Simples, Uma Mão, Corpo a Corpo, Arremesso, Alcance 5m", alcance=5),
    _arma("Martelo de Guerra", "19 Vo", "Martelos", "Força", 3, "concussao", 0,
          "Militar, Versátil, Corpo a Corpo", versatil=True),
    _arma("Picareta", "17 Vo", "Picaretas", "Força", 3, "perfuracao", 0,
          "Militar, Uma Mão, Corpo a Corpo"),
    _arma("Pique", "25 Vo", "Lanças", "Força", 4, "perfuracao", 1,
          "Militar, Duas Mãos, Corpo a Corpo, Haste"),
    _arma("Tridente", "15 Vo", "Lanças", "Força", 2, "perfuracao", 0,
          "Militar, Versátil, Corpo a Corpo, Arremesso, Alcance 5m", alcance=5, versatil=True),
    # -------------------- Outros Equipamentos de Batalha ----------------
    equipamento("Ariete de Mão", "Arma de Cerco", "17 Vo", 2,
                "Um tronco de madeira preso a elos de aço e com uma ponta de aço em uma das extremidades. Em suas laterais, há quatro alças de ferro permitindo quatro pessoas segurá-lo ao mesmo tempo.\n\nPropriedade: quando tenta derrubar uma porta usando este acessório, até três aliados podem prestar-lhe auxílio nesta tarefa.",
                img=IMG_WEAPON),
    equipamento("Balas de Funda", "Munição", "1 Va", 0,
                "Pequenas esferas de pedra utilizadas como munição para as fundas.\n\nPropriedade: uma vez disparada, a bala tem grandes chances de se despedaçar com o impacto, a menos que tenha uma propriedade mágica. É possível recuperar metade das balas utilizadas em um combate quando ele termina. Pagando 1 Va você tem balas suficientes para uma aventura.",
                img=IMG_ITEM),
    equipamento("Escudo de Madeira", "Escudo", "5 Vo", 0,
                "Uma base de madeira cuja parte traseira possui tiras de couro usadas para prendê-lo ao braço.\n\nPropriedade: Deflexão (resultados iguais em uma rolagem de Bloqueio reduzem 1 ponto no dano bruto sofrido).",
                notes="Deflexão", mode="active", img=IMG_ARMOR),
    equipamento("Escudo de Metal", "Escudo", "15 Vo", 1,
                "Uma base metálica cuja parte traseira possui tiras de couro ou elos de aço usadas para prendê-lo ao braço.\n\nPropriedade: Deflexão (resultados iguais em uma rolagem de Bloqueio reduzem 1 ponto no dano bruto sofrido).",
                notes="Deflexão", mode="active", img=IMG_ARMOR),
    equipamento("Flechas", "Munição", "1 Va", 0,
                "Pequenas hastes de madeira com pontas de metal pontiagudas. Utilizadas como munição para os arcos.\n\nPropriedade: uma vez disparada, a flecha se despedaça com o impacto, a menos que tenha uma propriedade mágica. Pagando 1 Va você tem flechas suficientes para uma aventura.",
                img=IMG_ITEM),
    equipamento("Manoplas de Segurança", "Manoplas", "15 Vo", 0,
                "Luvas de ligas de aço que possuem elos onde pode ser preso firmemente o cabo da arma.\n\nPropriedade: enquanto estiver usando este acessório, tentativas de desarmá-lo fracassam automaticamente.",
                mode="active", img=IMG_ARMOR),
    equipamento("Virotes", "Munição", "1 Va", 0,
                "Pequenas hastes de madeira com pontas de metal pontiagudas. Utilizadas como munição para as bestas.\n\nPropriedade: uma vez disparado, o virote se despedaça com o impacto, a menos que tenha uma propriedade mágica. Pagando 1 Va você tem virotes suficientes para uma aventura.",
                img=IMG_ITEM),
    equipamento("Estrepes", "Utensílio", "6 Va", 0,
                "Espinhos de metal em forma triangular.\n\nPropriedade: Alcance 5m. Você pode arremessá-los de forma a cobrir até 6 espaços, adjacentes entre eles. Qualquer criatura que adentrar essa área deve ser bem sucedida em uma rolagem de Agilidade (Difícil) para não ficar lenta até sair da área. Os estrepes podem ser recuperados após o combate; no entanto, cada novo uso terá a dificuldade da rolagem de Agilidade reduzida em 2 pontos e cobrirá 1 espaço a menos. Quando a quantidade de espaços cobertos chegar a 0, eles acabam.",
                img=IMG_TOOL),
    # ------------------------------ Ferramentas -------------------------
    equipamento("Ferramentas de Artesão", "Ferramentas", "30 Vo", 2,
                "Ferramentas adequadas a um determinado ofício de criação de itens.\n\nPropriedade: este equipamento é necessário para a criação de determinados tipos de itens. Sem ele não é possível produzi-los. Quando comprar estas ferramentas, você deve definir que tipo de artesanato elas produzem.\n\nTipos de Artesanato: Carpintaria, Cartografia, Costuraria, Couraria, Entalhe, Forjaria, Funilaria, Joalheria, Olaria, Alvenaria, Pintura, Sapataria, Vidraçaria, Alquimia, Cervejaria, Caligrafia, Cozinha, Venenos.",
                img=IMG_TOOL),
    equipamento("Ferramentas de Curtimento", "Ferramentas", "10 Vo", 1,
                "Um punhal, uma escova de cerdas de aço e um esticador.\n\nPropriedade: permite extrair e preparar couro de criaturas. A extração e preparo permite o gasto de 10 Vo a mais por dia de criação de um item de couro.",
                img=IMG_TOOL),
    equipamento("Ferramentas de Ladrão", "Ferramentas", "25 Vo", 0,
                "Inclui chaves mestras, alicates, tesouras e um pequeno espelho.\n\nPropriedade: enquanto estiver usando essas ferramentas, você recebe +1 nas rolagens para arrombar fechaduras.",
                img=IMG_TOOL),
    equipamento("Ferramentas de Lenharia", "Ferramentas", "10 Vo", 1,
                "Inclui serrote, machado de lenhador, talhadeira e canivete.\n\nPropriedade: permite extrair e preparar madeira. A extração e preparo permite o gasto de 10 Vo a mais por dia de criação de um item de madeira.",
                img=IMG_TOOL),
    equipamento("Ferramentas de Mineração", "Ferramentas", "30 Vo", 1,
                "Inclui luvas de couro, pá, elmo de minerador e uma picareta de mineração.\n\nPropriedade: permite extrair minerais. A extração permite o gasto de 10 Vo a mais por dia de criação de um item de metal.",
                img=IMG_TOOL),
    equipamento("Ferramentas de Navegação", "Ferramentas", "25 Vo", 0,
                "Inclui uma luneta, um anemômetro e uma bússola.\n\nPropriedade: enquanto estiver usando essas ferramentas, você recebe +1 em rolagens para traçar um curso de navegação e para não se perder no mar.",
                img=IMG_TOOL),
    equipamento("Kit de Disfarces", "Ferramentas", "25 Vo", 0,
                "Tinta de cabelo, maquiagem, vestimentas e adereços que mudam sua aparência.\n\nPropriedade: enquanto estiver usando esses itens, você recebe +1 nas rolagens para se disfarçar.",
                img=IMG_TOOL),
    equipamento("Kit de Primeiros Socorros", "Ferramentas", "1 Va", 0,
                "Ataduras, unguentos, bandagens, pinças, lâminas devidamente higienizadas e frascos alquímicos que aceleram a cicatrização.\n\nPropriedade: quando você realiza uma rolagem de cuidados médicos para cuidar de um aliado usando esse kit, você recebe +1 nessa rolagem. Este item é consumido quando utilizado.",
                img=IMG_TOOL),
    # ------------------------------ Outros Itens ------------------------
    equipamento("Algibeira (vazia)", "Compartimento", "1 Va", 0,
                "Uma pequena bolsa de couro que pode ser anexada ao cinto.\n\nPropriedade: compartimento suficiente para guardar até 30 moedas, balas de funda suficientes para uma aventura ou três frascos de remédio, antídoto, poção, elixir ou óleo. Enquanto guardados neste compartimento, os itens podem ser sacados com uma ação rápida.",
                img=IMG_ITEM),
    equipamento("Aljava (vazia)", "Compartimento", "1 Va", 0,
                "Um cone comprido de couro, com uma alça longa, que permite carregá-lo nas costas.\n\nPropriedade: compartimento que permite guardar flechas suficientes para uma aventura. Enquanto guardadas neste compartimento, as flechas podem ser sacadas dele com uma ação livre.",
                img=IMG_ITEM),
    equipamento("Ampulheta", "Dispositivo", "5 Vo", 0,
                "Um pequeno frasco de vidro com bases de madeira em suas extremidades, contendo areia, usado para contar o tempo.\n\nPropriedade: permite calcular o tempo de 1 minuto.",
                img=IMG_ITEM),
    equipamento("Arpéu", "Utensílio", "2 Vo", 0,
                "Peça de metal com quatro ganchos, usada para amarrar a uma corda ou corrente.\n\nPropriedade: caso seja usado amarrado a uma corda ou corrente, concede +1 em rolagens para escalar.",
                img=IMG_TOOL),
    equipamento("Bolsa de Componentes", "Compartimento", "20 Vo", 0,
                "Bolsa contendo vários materiais usados em conjuração de magias.\n\nPropriedade: requisito alternativo ao foco em conjuração de magias de Círculo Maior.",
                img=IMG_ITEM),
    equipamento("Bastão", "Foco", "20 Vo", 0,
                "Uma haste curta de madeira, metal ou qualquer outro tipo de material rígido.\n\nPropriedade: um objeto utilizado por conjuradores como componente para a conjuração de magias de Círculo Maior. Deve ser empunhado com uma mão.",
                img=IMG_ITEM),
    equipamento("Caixa de Fogo", "Utensílio", "1 Va", 0,
                "Um recipiente contendo uma pederneira e um isqueiro.\n\nPropriedade: pode ser usado para acender tochas ou qualquer outro objeto contendo combustível, gastando uma ação. Objetos sem combustível levam uma cena para pegar fogo.",
                img=IMG_TOOL),
    equipamento("Cajado", "Foco", "20 Vo", 0,
                "Uma haste longa de madeira, metal ou qualquer outro tipo de material rígido. Normalmente possui alguma joia incrustada em uma de suas extremidades.\n\nPropriedade: um objeto utilizado por conjuradores como componente para a conjuração de magias de Círculo Maior. Pode ser usado como arma de duas mãos, com dano base Concussão +1. Como foco, pode ser empunhado com uma mão.",
                actions=[action("Ataque — Cajado (Concussão +1)", roll_attr="forca",
                                damage="1", damage_type="concussao",
                                defense_attr="esquiva", defense_attr2="bloqueio")],
                img=IMG_ITEM),
    equipamento("Cantil", "Compartimento", "2 Va", 0,
                "Bolsa de couro impermeável contendo um bico anelado e uma tampa para o mesmo.\n\nPropriedade: permite carregar água suficiente para uma aventura.",
                img=IMG_ITEM),
    equipamento("Corda", "Utensílio", "1 Va", 0,
                "Corda feita em cânhamo trançado.\n\nPropriedade: corda de 15m de comprimento com Dureza 2.",
                img=IMG_TOOL),
    equipamento("Corrente", "Utensílio", "1 Vo", 1,
                "Elos de metal entrelaçados.\n\nPropriedade: corrente de 15m de comprimento.",
                img=IMG_TOOL),
    equipamento("Espelho", "Utensílio", "5 Vo", 0,
                "Base de aço espelhado, com cabo inteiriço.\n\nPropriedade: usado para refletir imagens, pode ser utilizado como foco para magias compostas por iluzio. Para ser usado como foco, deve ser empunhado com uma mão.",
                img=IMG_ITEM),
    equipamento("Grimório (vazio)", "Compartimento", "50 Vo", 0,
                "Um livro com capa de couro resistente e várias páginas em branco.\n\nPropriedade: item necessário para anotar magias aprendidas e criadas. Um conjurador que não tenha a posse do seu grimório não poderá conjurar suas magias de Círculo Intermediário e Maior.",
                img=IMG_ITEM),
    equipamento("Instrumento Musical", "Dispositivo", "20 Vo", 0,
                "Aparato utilizado para se produzir sons, seja um alaúde, flauta, oboé, tambor, etc.\n\nPropriedade: utilizado em performances musicais. Também pode ser utilizado como foco na conjuração de magias de Círculo Maior, quando empunhado com as duas mãos e tocado, substituindo também o componente gestual.",
                img=IMG_ITEM),
    equipamento("Lanterna", "Dispositivo", "5 Vo", 0,
                "Uma lanterna coberta que queima óleo para produzir luz.\n\nPropriedade: este item ilumina num raio de 10m. Um frasco de óleo dura 1 hora. Ela pode ser empunhada com uma das mãos, apoiada em uma superfície sólida ou ser mantida suspensa por alguma corda ou gancho.",
                img=IMG_ITEM),
    equipamento("Mochila (vazia)", "Compartimento", "2 Vo", 0,
                "Bolsa grande de couro contendo vários compartimentos.\n\nPropriedade: esta bolsa contém compartimentos usados para guardar itens que não estejam em uso.",
                img=IMG_ITEM),
    equipamento("Óleo", "Material", "1 Va", 0,
                "Frasco de óleo utilizado como combustível da lanterna.\n\nPropriedade: se usado em uma lanterna como combustível, permite mantê-la acesa por 1 hora.",
                img=IMG_ITEM),
    equipamento("Orbe", "Foco", "20 Vo", 0,
                "Uma esfera em material mineral. Pode ser transparente ou opaca.\n\nPropriedade: um objeto utilizado por conjuradores como componente para a conjuração de magias de Círculo Maior. Deve ser empunhado com uma das mãos.",
                img=IMG_ITEM),
    equipamento("Pergaminho (em branco)", "Material", "1 Va", 0,
                "Feito em papel, usado para escrever mensagens e magias.\n\nPropriedade: item utilizado para escrever mensagens e armazenar magias. Para armazenar uma magia em um pergaminho, o conjurador deve pagar os pontos de magia necessários para conjurá-la. O processo requer uma hora para concluir a tarefa. Após armazenada no pergaminho, a magia não consome pontos de magia para ser conjurada, queimando o pergaminho na conjuração.",
                img=IMG_ITEM),
    equipamento("Porta Virotes (vazio)", "Compartimento", "1 Vo", 0,
                "Estojo de madeira feito para armazenar virotes.\n\nPropriedade: compartimento que permite guardar virotes suficientes para uma aventura. Enquanto guardados neste compartimento, os virotes podem ser sacados dele com uma ação livre.",
                img=IMG_ITEM),
    equipamento("Pacote de Explorador", "Conjunto", "8 Vo", 0,
                "Uma mochila contendo o básico necessário para uma viagem.\n\nPropriedade: uma mochila contendo um saco de dormir, um cantil, uma corda, uma tocha, uma caixa de fogo e dez dias de ração de viagem.",
                img=IMG_ITEM),
    equipamento("Rações de Viagem", "Suprimento", "5 Va", 0,
                "Comida desidratada, que resiste mais ao tempo que comida normal.\n\nPropriedade: refeição suficiente para um personagem por um dia.",
                img=IMG_ITEM),
    equipamento("Remédio", "Suprimento", "20 Vo", 0,
                "Um frasco contendo um medicamento líquido que, quando ingerido, melhora a recuperação do personagem.\n\nPropriedade: quando ingerido, equivale a uma rolagem bem sucedida de cuidados médicos.",
                img=IMG_ITEM),
    equipamento("Roupas Comuns", "Vestimenta", "5 Va", 0,
                "Camisa, manto, calça ou saia, e um chapéu ou capuz.\n\nPropriedade: vestes de pessoas comuns.",
                img=IMG_ITEM),
    equipamento("Roupas de Viajante", "Vestimenta", "2 Vo", 0,
                "Trajes muito utilizados por aventureiros, contendo uma camisa ou robe com muitos bolsos, calças, botas e um manto com capuz.\n\nPropriedade: trajes para aventureiros, normalmente mais resistentes que os trajes comuns.",
                img=IMG_ITEM),
    equipamento("Saco de Dormir", "Utensílio", "1 Vo", 0,
                "Um enorme saco de couro e peles, utilizado para manter-se aquecido e confortável durante o descanso.\n\nPropriedade: requisito para um sono adequado durante as viagens.",
                img=IMG_ITEM),
    equipamento("Símbolo Sagrado / Profano", "Foco", "20 Vo", 0,
                "Um símbolo de uma divindade entalhado em madeira ou metal.\n\nPropriedade: um objeto utilizado por clérigos para canalizar os poderes de aspecto de sua divindade e por conjuradores ligados a uma religião, como componente para a conjuração de magias de Círculo Maior. Um símbolo sagrado refere-se a uma divindade boa. Um símbolo profano refere-se a uma divindade maligna. Deve ser empunhado com uma das mãos.",
                img=IMG_ITEM),
    equipamento("Tocha", "Suprimento", "1 Vn", 0,
                "Haste grossa de madeira, contendo um tecido enrolado em uma das extremidades, imbuído com combustível.\n\nPropriedade: este item ilumina num raio de 5m e dura 1 hora.",
                img=IMG_ITEM),
    equipamento("Totem", "Foco", "20 Vo", 0,
                "Pequeno tronco de madeira entalhado em imagens comumente relacionadas aos espíritos da natureza.\n\nPropriedade: um objeto utilizado por conjuradores como componente para a conjuração de magias de Círculo Maior. Deve ser empunhado com uma das mãos.",
                img=IMG_ITEM),
    equipamento("Varinha", "Foco", "20 Vo", 0,
                "Uma curta e fina haste feita em madeira, metal ou outro tipo de material rígido.\n\nPropriedade: um objeto utilizado por conjuradores como componente para a conjuração de magias de Círculo Maior. Deve ser empunhado com uma mão.",
                img=IMG_ITEM),
    # ------------------------------ Montarias ---------------------------
    equipamento("Pônei", "Montaria", "30 Vo", 0,
                "Montaria de pequeno porte.\n\nCarga: 8. Deslocamento: 9m. Enquanto estiver montado, use o Deslocamento da montaria no lugar do Deslocamento do personagem.",
                notes="Carga 8 · Deslocamento 9m", img=IMG_MOUNT),
    equipamento("Cavalo de Montaria", "Montaria", "50 Vo", 0,
                "Montaria comum para viagens.\n\nCarga: 9. Deslocamento: 12m. Enquanto estiver montado, use o Deslocamento da montaria no lugar do Deslocamento do personagem.",
                notes="Carga 9 · Deslocamento 12m", img=IMG_MOUNT),
    equipamento("Camelo", "Montaria", "75 Vo", 0,
                "Montaria adaptada a climas áridos.\n\nCarga: 9. Deslocamento: 12m. Enquanto estiver montado, use o Deslocamento da montaria no lugar do Deslocamento do personagem.",
                notes="Carga 9 · Deslocamento 12m", img=IMG_MOUNT),
    equipamento("Cavalo de Guerra", "Montaria", "400 Vo", 0,
                "Montaria treinada para o combate.\n\nCarga: 10. Deslocamento: 15m. Enquanto estiver montado, use o Deslocamento da montaria no lugar do Deslocamento do personagem.",
                notes="Carga 10 · Deslocamento 15m", img=IMG_MOUNT),
]

SERVICOS = [
    ("Carne", "2 Va"), ("Cerveja", "1 Vn"), ("Estalagem Pobre", "1 Vn"),
    ("Estalagem Mediana", "5 Va"), ("Estalagem Rica", "2 Vo"),
    ("Guia", "1 Vn por Km"), ("Mensageiro", "1 Va por Km"), ("Pedágio", "1 Vn"),
    ("Reparos nos Equipamentos", "1000"), ("Refeição Diária", "3 Va"),
    ("Serviçal", "2 Va por dia"), ("Vinho", "1 Va"),
]

EQUIPAMENTOS += [
    equipamento(f"Serviço: {nome}", "Serviço", preco, 0,
                f"Serviço ou profissional contratado durante as aventuras. Preço: {preco}.",
                img=IMG_SERVICE)
    for nome, preco in SERVICOS
]
